Added My Card
Syknapse/Contribute-To-This-Project pull request #1073
Opened 2021-11-18 09:49 UTC by MahimaKhatri

Details Added

2021-11-19 09:38 UTC, iatharva requested changes
Looks like you have added your card at the end of the file, you have to add your card just below the template as per instructions given in step 5, you can check it [here](https://github.com/Syknapse/Contribute-To-This-Project/).
Once the changes are done, We'll review the PR and merge it.

2021-11-20 05:04 UTC, MahimaKhatri commented
The necessary changes are done. Please Review.

2021-11-20 09:43 UTC, iatharva approved these changes

2021-11-20 09:49 UTC, iatharva commented
Looks good! Thank you for the contribution and welcome to open source :)

2021-11-20 09:49 UTC, merged