Adding my card
Syknapse/Contribute-To-This-Project pull request #1084
Opened 2021-12-01 15:07 UTC by VesnaBozic

2021-12-01 19:40 UTC, VesnaBozic commented
Adding  Serbian translation

2021-12-05 17:59 UTC, iatharva requested changes
Looks like you have added your card at the end of the file, you have to add your card just below the template as per instructions given in step 5, you can check it [here](https://github.com/Syknapse/Contribute-To-This-Project/).
Other than that looks good.

2021-12-06 16:14 UTC, iatharva approved these changes

2021-12-06 17:13 UTC, iatharva approved these changes

2021-12-06 17:16 UTC, iatharva commented
Thank you for your contribution, it's really helpful 💯

2021-12-06 17:16 UTC, merged