Cesar959: Adicionou as informações do meu cartão
Syknapse/Contribute-To-This-Project pull request #1103
Opened 2022-01-07 15:53 UTC by Cesar959

Minha contribução com o projeto open source, adicionando o meu cartão.

2022-02-13 21:54 UTC, confused-Techie commented
@Cesar959 This commit looks fantastic, Obrigada and congrats on your first contribution to an open source project! 🎉

2022-02-14 04:20 UTC, iatharva requested changes
Looks like you have added your card at the end of the file, you have to add your card just below the template as per instructions given in step 5, you can check it [here](https://github.com/Syknapse/Contribute-To-This-Project/).
Once the changes are done, We'll review the PR and merge it.

2022-02-14 10:23 UTC, Cesar959 commented
Bom dia! fiz a correção do conflito como informado.
Obrigado.

2022-02-14 10:53 UTC, iatharva approved these changes

2022-02-14 23:23 UTC, merged