Ziv kaplan card
Syknapse/Contribute-To-This-Project pull request #1108
Opened 2022-01-13 11:04 UTC by zivkaplan

My new card, fixed.

2022-02-14 04:22 UTC, iatharva requested changes
Looks like you have directly modified the template which you have to copy, you have to add your card just below the template as per instructions given in step 5, you can check it [here](https://github.com/Syknapse/Contribute-To-This-Project/).
Once the changes are done, We'll review the PR and merge it.

2022-02-14 07:37 UTC, zivkaplan commented
Hi, 
thank you.,
Hopefully it is fine now.

2022-02-14 10:52 UTC, iatharva approved these changes

2022-03-26 05:26 UTC, merged

2022-03-26 05:27 UTC, iatharva commented
Thank you for your contribution!