added my card information
Syknapse/Contribute-To-This-Project pull request #1154
Opened 2022-03-07 14:09 UTC by nura-rikuo

2022-03-25 11:46 UTC, dilshankarunarathne requested changes
The code template was covered with 
`<!-- ________ *TEMPLATE: MAKE A COPY* Contributor card START ________  -->` and
`<!-- ________*END TEMPLATE* Contributor card END ________  -->` comments.
These comments are very helpful for future contributors and maintainers to read and understand the code. 
So, please include those comments in your card as well. 
And make sure to change `*TEMPLATE: MAKE A COPY*` and `*END TEMPLATE*` parts into your name.

2022-03-25 11:46 UTC, dilshankarunarathne commented on index.html
> +
Looks like you did not include the comments at the start and end of the template.

2022-03-25 11:47 UTC, dilshankarunarathne commented
Hello @nura-rikuo, 
we will be able to review and merge your pull request once you make these changes.

2022-05-14 11:49 UTC, merged

2022-05-14 11:50 UTC, Preet-Sojitra commented
Congratulations @nura-rikuo for your contribution in open source. Best of luck for your future journey in open source :)