Kris' card
Syknapse/Contribute-To-This-Project pull request #1163
Opened 2022-03-12 22:56 UTC by kik369

added my card to index.html

2022-04-03 05:43 UTC, dilshankarunarathne requested changes
Hello @kik369, please make these changes and get back to us.
We will be able to review and merge your pull request after that.

2022-04-03 05:43 UTC, dilshankarunarathne commented on index.html
> +        <!-- ________*END TEMPLATE* Contributor card END ________  -->
You should leave a blank line between your code and other codes.

2022-04-03 05:43 UTC, dilshankarunarathne commented on index.html
> +        <!-- ________ *TEMPLATE: MAKE A COPY* Contributor card START ________  -->
Please change this comment 
`<!-- ________ *TEMPLATE: MAKE A COPY* Contributor card START ________ -->`
into `<!-- ________ YourName Contributor card START ________ -->`

2022-04-03 05:43 UTC, dilshankarunarathne commented on index.html
> +        <!-- ________*END TEMPLATE* Contributor card END ________  -->
Please change (add your name) this comment as well. 
Otherwise everyone will have a hard time identifying your code.

2022-04-03 05:43 UTC, dilshankarunarathne commented on index.html
> +        <!-- ________ *TEMPLATE: MAKE A COPY* Contributor card START ________  -->
You should leave a blank line between your code and the template.

2022-05-14 12:02 UTC, Preet-Sojitra commented
@kik369 Your current pr is causing around 30 merge conflicts. You are requested to add your card again and open a new pr. Once you open a new pr we will merge it.
I am closing this current pr.
Thank you

2022-05-14 12:02 UTC, closed without merging