Tim's card initial commit
Syknapse/Contribute-To-This-Project pull request #1166
Opened 2022-03-15 01:18 UTC by tcas2162

Added my card information. Included links to three Youtube channels that have helped me on my coding journey

2022-03-24 12:28 UTC, dilshankarunarathne requested changes
Your commit has re-formatted the previous code, by adding whitespaces and new lines.

2022-03-24 12:28 UTC, dilshankarunarathne commented on index.html
> +        <!-- ________ *Tim's card START ________  -->
It looks like you've added your card at the end of the page.

2022-05-15 10:43 UTC, Preet-Sojitra commented
@tcas2162 your pr is causing around 40 merge conflicts, which is kinda difficult to solve. So you are requested to open a new pull request. Once you open a new pull request, we will merge it. 
Thank you

2022-07-13 20:12 UTC, win21H2 commented
Will close this PR and try to injest the HTML code. REASON FOR CLOSE: This issue has been open and changes have not been made since March 24

2022-07-13 20:12 UTC, closed without merging