Add my card information
Syknapse/Contribute-To-This-Project pull request #1208
Opened 2022-04-06 17:04 UTC by KyrtovaLera

2022-04-06 17:15 UTC, dilshankarunarathne requested changes
Hello @KyrtovaLera, once you make these changes - please get back to us, we will be able to review and merge your pull request.

2022-04-06 17:15 UTC, dilshankarunarathne commented on index.html
> +        <!-- ________*END TEMPLATE* Contributor card END ________  -->
Please change this comment too, by adding your name here.

2022-04-06 17:15 UTC, dilshankarunarathne commented on index.html
>          <!-- ________ Shiva's card START ________  -->
Blank lines are important when others read this code afterwards.

2022-04-06 17:15 UTC, dilshankarunarathne commented on index.html
>          <!-- ========== ⬇⬇ Paste YOUR CARD directly BELOW this line ⬇⬇ ========== -->
Please leave blank lines around your card as per the instructions (one line before - and one line after).

2022-05-15 11:42 UTC, merged

2022-05-15 11:42 UTC, Preet-Sojitra commented
Congrtulations @KyrtovaLera  your pr has been merged. Have a nice day ahead :)