Rodolpho's Card
Syknapse/Contribute-To-This-Project pull request #1211
Opened 2022-04-13 16:12 UTC by rodolphonapoleon

Added my card information to the index.html file

2022-04-14 06:28 UTC, dilshankarunarathne requested changes
Hello @rodolphonapoleon, thank you for contributing to this project.
You need to make a couple of simple changes to your code before we go ahead and merge your pull request.
Please change these two comments, they help everyone to identify the cards of each contributor. 
Once you made those changes, get back to us. We will be able to review and merge your pull request in a flash.

2022-04-14 06:28 UTC, dilshankarunarathne commented on index.html
> +        <!-- ________ *TEMPLATE: MAKE A COPY* Contributor card START ________  -->
Please change this comment to 
`<!-- ________ Your Name Contributor card START ________ -->`

2022-04-14 06:28 UTC, dilshankarunarathne commented on index.html
> +        <!-- ________*END TEMPLATE* Contributor card END ________  -->
Please change this comment to 
`<!-- ________ Your Name Contributor card END________ -->`

2022-05-17 09:36 UTC, Preet-Sojitra commented
@rodolphonapoleon Your current pull request is causing around 40 merge conflicts. So you are requested to open a new pull request, once you open new pull request, we will merge it.
Thank you :)

2022-05-21 05:10 UTC, Preet-Sojitra commented
> I fixed my issue

Merge conflicts aren't solve yet. Please open new pull request. In order to open new pull request, you need to make new branch, and then commit your changes, because one branch can open only one pull request.

2022-07-20 06:27 UTC, win21H2 commented
Hello @rodolphonapoleon, I will be closing this issue since it has 100+ conflicts although I will manually add it to the website :)

2022-07-20 06:27 UTC, closed without merging