Update index.html
Syknapse/Contribute-To-This-Project pull request #1212
Opened 2022-04-14 01:23 UTC by scottbdavis

Added new card for scott

2022-04-14 06:23 UTC, dilshankarunarathne approved these changes

2022-04-14 06:29 UTC, dilshankarunarathne approved these changes

2022-04-14 06:35 UTC, dilshankarunarathne requested changes
Hello @scottbdavis, thank you for contributing to this project. Your code is fine. But you have not filled in the required details for your contributor card.
Please fill it out and get back to us. We will be able to review and merge your pull request after that.

2022-05-15 16:21 UTC, merged

2022-05-15 16:22 UTC, Preet-Sojitra commented
Congratulations 🎉🎉 @scottbdavis  your pull request has been merged. Have a great day ahead :)

2022-05-16 21:52 UTC, scottbdavis commented
Thanks 🙏

On Sun, May 15, 2022 at 12:21 PM Preet Sojitra ***@***.***>
wrote:

> Merged #1212
> <https://github.com/Syknapse/Contribute-To-This-Project/pull/1212> into
> master.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Syknapse/Contribute-To-This-Project/pull/1212#event-6611528829>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE5JAJQYPMFZQQEQCIZ6VULVKEQBNANCNFSM5TMJ5HGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> <Syknapse/Contribute-To-This-Project/pull/1212/issue_event/6611528829@
> github.com>
>