Chris Small's card
Syknapse/Contribute-To-This-Project pull request #1235
Opened 2022-04-24 18:05 UTC by CodingComrade

added my card to index.html

2022-04-25 02:51 UTC, dilshankarunarathne requested changes
Hello @CodingComrade, thank you for contributing to this project.
But it looks like you have added your card right at the bottom of the HTML file. Please follow the instructions carefully and move your code up, so it would be the most recently added card. 
Once you are done, get back to us. We will be able to review and merge your pull request in a flash.

2022-04-25 15:25 UTC, CodingComrade commented
> Hello @CodingComrade, thank you for contributing to this project. But it looks like you have added your card right at the bottom of the HTML file. Please follow the instructions carefully and move your code up, so it would be the most recently added card. Once you are done, get back to us. We will be able to review and merge your pull request in a flash.

I apologize for the mistake, I missed those instructions the first time around. I believe the latest pull request should resolve the issue.

2022-04-26 02:53 UTC, dilshankarunarathne approved these changes

2022-04-26 02:54 UTC, merged

2022-04-26 02:54 UTC, dilshankarunarathne commented
Congratulations 🎉❤ @CodingComrade. 
Your pull request was merged. 
You will be able to see your card on the [project website](https://syknapse.github.io/Contribute-To-This-Project/).