Abel Roy's Card
Syknapse/Contribute-To-This-Project pull request #1239
Opened 2022-04-25 17:47 UTC by AbelR007

Added a new card with helpful information on Web Development.

2022-04-26 03:07 UTC, dilshankarunarathne requested changes
Hello @AbelR007, thank you for contributing to this project. ❤
But there are a couple of small changes that need to be done before we go ahead and merge your code. Please change these two comments, because they are very helpful for everyone to identify each card. 
Once you've made those changes, please get back to us. We will be able to review and merge your pull request in a flash.

2022-04-26 03:07 UTC, dilshankarunarathne commented on index.html
> +        <!-- ________ *TEMPLATE: MAKE A COPY* Contributor card START ________  -->
Please change this comment 
`<!-- ________ *TEMPLATE: MAKE A COPY* Contributor card START ________ -->` 
into `<!-- ________ Your_Name Contributor card START ________ -->`

2022-04-26 03:07 UTC, dilshankarunarathne commented on index.html
> +        <!-- ________*END TEMPLATE* Contributor card END ________  -->
Please change this comment as well. 
`<!-- ________*END TEMPLATE* Contributor card END ________ -->` 
to `<!-- ________ Your_Name Contributor card END ________ -->`

2022-04-26 17:01 UTC, AbelR007 commented
Thanks, @dilshankarunarathne  for responding,
I have corrected the card with the proper comments!

2022-04-27 03:20 UTC, dilshankarunarathne approved these changes

2022-04-27 03:22 UTC, merged

2022-04-27 03:22 UTC, dilshankarunarathne commented
Congratulations 🎉❤
Your pull request was merged. 
You will be able to see your card on the [project website](https://syknapse.github.io/Contribute-To-This-Project/).