Harun J add card (flexton1)
Syknapse/Contribute-To-This-Project pull request #1241
Opened 2022-04-25 22:27 UTC by flexton1

Added card into index.html

2022-04-25 22:29 UTC, flexton1 commented
-thank you

2022-04-26 03:03 UTC, dilshankarunarathne requested changes
Hello @flexton1, thank you for contributing to this project. ❤
But it looks like you have added your card at the bottom of the HTML file. Please read the instructions carefully again, and move your code up, so it would be the most recently added card. 
Once you've made those changes, please get back to us. We will be able to review and merge your pull request in a flash.

2022-04-29 02:50 UTC, dilshankarunarathne approved these changes

2022-04-29 02:51 UTC, merged

2022-04-29 02:51 UTC, dilshankarunarathne commented
Congratulations 🎉❤
Your pull request was merged. 
You will be able to see your card on the [project website](https://syknapse.github.io/Contribute-To-This-Project/).