Foolnidiot card
Syknapse/Contribute-To-This-Project pull request #1245
Opened 2022-04-26 16:05 UTC by foolnidiot

2022-04-26 16:05 UTC, foolnidiot commented
Added my card

2022-04-27 03:18 UTC, dilshankarunarathne requested changes
Hello @foolnidiot, thank you for contributing to this project. ❤
But there are a couple of small changes that need to be done before we go ahead and merge your code. Please change these two comments, because they are very helpful for everyone to identify each card. 
Leaving two blank lines around your code is also important. 
Once you've made those changes, please get back to us. We will be able to review and merge your pull request in a flash.

2022-04-27 03:18 UTC, dilshankarunarathne commented on index.html
> +<!-- ________ *TEMPLATE: MAKE A COPY* Contributor card START ________  -->
Please change this comment 
`<!-- ________ *TEMPLATE: MAKE A COPY* Contributor card START ________ -->` 
into `<!-- ________ Your_Name Contributor card START ________ -->`

2022-04-27 03:18 UTC, dilshankarunarathne commented on index.html
> +<!-- ________*END TEMPLATE* Contributor card END ________  -->
Please change this comment as well. 
`<!-- ________*END TEMPLATE* Contributor card END ________ -->` 
to `<!-- ________ Your_Name Contributor card END ________ -->`

2022-04-27 03:18 UTC, dilshankarunarathne commented on index.html
>          <!-- ========== ⬇⬇ Paste YOUR CARD directly BELOW this line ⬇⬇ ========== -->
Please leave an empty line between the template and your code.

2022-04-27 03:18 UTC, dilshankarunarathne commented on index.html
>          <!-- ________ ComradeGuero's card START ________  -->
Please leave an empty line after your code.

2022-04-29 02:53 UTC, dilshankarunarathne approved these changes

2022-04-29 02:55 UTC, merged

2022-04-29 02:55 UTC, dilshankarunarathne commented
Congratulations 🎉❤
Your pull request was merged. 
You will be able to see your card on the [project website](https://syknapse.github.io/Contribute-To-This-Project/).