Oluwaseyi's card
Syknapse/Contribute-To-This-Project pull request #1267
Opened 2022-05-06 11:46 UTC by emperor6inch

2022-05-07 04:49 UTC, dilshankarunarathne requested changes
Hello @emperor6inch, thank you for contributing to this project. ❤
But there are a couple of small changes that need to be done before we go ahead and merge your code. Please change these two comments, because they are very helpful for everyone to identify each card. 
Once you've made those changes, please get back to us. We will be able to review and merge your pull request in a flash.

2022-05-07 04:49 UTC, dilshankarunarathne commented on index.html
> +                <!-- ________ *TEMPLATE: MAKE A COPY* Contributor card START ________  -->
Please change this comment 
`<!-- ________ *TEMPLATE: MAKE A COPY* Contributor card START ________ -->` 
into `<!-- ________ Your_Name Contributor card START ________ -->`

2022-05-07 04:49 UTC, dilshankarunarathne commented on index.html
> +                <!-- ________*END TEMPLATE* Contributor card END ________  -->
Please change this comment as well. 
`<!-- ________*END TEMPLATE* Contributor card END ________ -->` 
to `<!-- ________ Your_Name Contributor card END ________ -->`

2022-05-13 13:33 UTC, emperor6inch reviewed
Thank you so much

2022-05-14 03:48 UTC, dilshankarunarathne approved these changes

2022-05-14 03:50 UTC, merged

2022-05-14 03:51 UTC, dilshankarunarathne commented
Congratulations 🎉❤ @emperor6inch.
Your pull request was merged. 
You will be able to see your card on the [project website](https://syknapse.github.io/Contribute-To-This-Project/).