Salman's Info Card
Syknapse/Contribute-To-This-Project pull request #1285
Opened 2022-05-16 19:19 UTC by MrPancakes39

Added a new card that contains my information to ```index.html```

2022-05-17 03:26 UTC, dilshankarunarathne requested changes
Hello @MrPancakes39, thank you for contributing to this project. ❤
But it looks like you have added your card at the bottom of the HTML file. Please read the instructions carefully again, and move your code up, so it would be the most recently added card. 
Once you've made those changes, please get back to us. We will be able to review and merge your pull request in a flash.

2022-05-17 07:10 UTC, MrPancakes39 commented
Hello @dilshankarunarathne! Sorry about the inconvenience, fixed it right away.
Thanks @Syknapse for this wonderful tutorial! ❤️

2022-05-18 01:44 UTC, dilshankarunarathne approved these changes

2022-05-18 01:45 UTC, merged

2022-05-18 01:45 UTC, dilshankarunarathne commented
Congratulations 🎉❤ @MrPancakes39.
Your pull request was merged. 
You will be able to see your card on the [project website](https://syknapse.github.io/Contribute-To-This-Project/).