Add my card information
Syknapse/Contribute-To-This-Project pull request #1287
Opened 2022-05-17 18:59 UTC by leeyoonj

2022-05-18 01:42 UTC, dilshankarunarathne requested changes
Hello @leeyoonj, thank you for contributing to this project. ❤
But there are a couple of small changes that need to be done before we go ahead and merge your code. Please change these two comments, because they are very helpful for everyone to identify each card. 
Once you've made those changes, please get back to us. We will be able to review and merge your pull request in a flash.

2022-05-18 01:42 UTC, dilshankarunarathne commented on index.html
> +        <!-- ________ *TEMPLATE: MAKE A COPY* Contributor card START ________  -->
Please change this comment 
`<!-- ________ *TEMPLATE: MAKE A COPY* Contributor card START ________ -->` 
into `<!-- ________ Your_Name Contributor card START ________ -->`

2022-05-18 01:42 UTC, dilshankarunarathne commented on index.html
> +        <!-- ________*END TEMPLATE* Contributor card END ________  -->
Please change this comment as well. 
`<!-- ________*END TEMPLATE* Contributor card END ________ -->` 
to `<!-- ________ Your_Name Contributor card END ________ -->`

2022-05-22 19:56 UTC, leeyoonj commented
changes made

2022-05-24 13:21 UTC, merged

2022-05-24 13:21 UTC, Preet-Sojitra commented
Congratulationss @leeyoonj Your pull request has been merged. Thanks for contribution :)