Add my card info
Syknapse/Contribute-To-This-Project pull request #1337
Opened 2022-06-15 16:42 UTC by zelalemMK

2022-06-15 16:42 UTC, zelalemMK commented
This is cool.

2022-07-17 07:11 UTC, TenTraicion commented on index.html
> +
add `<!-- ________*Zelalem* Contributor card END ________  --> after the end of your card

2022-07-17 07:12 UTC, TenTraicion commented on index.html
> +        <!-- ________ *TEMPLATE: MAKE A COPY* Contributor card START ________  -->
edit `<!-- ________ *TEMPLATE: MAKE A COPY* Contributor card START ________ -->` at the start of your card
change `TEMPLATE: MAKE A COPY` with your name

2022-07-17 07:13 UTC, TenTraicion requested changes
Kindly resolve the issues!

2022-07-18 12:50 UTC, merged