unmesh's card
Syknapse/Contribute-To-This-Project pull request #1528
Opened 2022-08-20 12:02 UTC by unm07

2022-08-20 12:05 UTC, nzaih1999 requested changes
hello @unm07 thanks for your contribution. Would you please move your code to the top of the file? ..

2022-08-20 12:07 UTC, TenTraicion requested changes
kindly put your card on top of the card section where it says `Paste Your Card Below This Line` after line 117.
Do the changes and commit!

2022-08-20 12:07 UTC, TenTraicion commented on index.html
> +            <a href="https://www.twitter.com/" target="_blank">@unmesh_07</a>
Kindly add your twitter username in the end of the twitter href link

2022-08-21 14:57 UTC, TenTraicion approved these changes

2022-08-21 14:57 UTC, merged

2022-08-21 14:57 UTC, TenTraicion commented
@unm07, Thanks for your Contribution. and Congrats on your first PR Merge in this project. Your Card will be live within ~2-3 minutes, which can be found: [Here](https://syknapse.github.io/Contribute-To-This-Project/)!