Add my card information.
Syknapse/Contribute-To-This-Project pull request #1536
Opened 2022-08-22 04:01 UTC by amersfoort3232

Add my card to index.html

2022-08-22 04:04 UTC, TenTraicion requested changes
kindly do the recommended changes and commit.

2022-08-22 04:04 UTC, TenTraicion commented on index.html
> +        <!-- ________ *TEMPLATE: MAKE A COPY* Contributor card START ________  -->
```suggestion

        <!-- ________ *Amersfoort* Contributor card START ________  -->
```

2022-08-22 04:04 UTC, TenTraicion commented on index.html
> +        <!-- ________*END TEMPLATE* Contributor card END ________  -->
```suggestion
        <!-- ________*Amersfoort* Contributor card END ________  -->
        
```

2022-08-23 07:17 UTC, nzaih1999 approved these changes

2022-08-23 07:20 UTC, nzaih1999 commented
Hello @amersfoort3232 I did some little changes on your PR. Your changes are now ready for merge. Thanks for your contribution. Happy Coding

2022-08-23 07:21 UTC, merged