zyad contribution
Syknapse/Contribute-To-This-Project pull request #1538
Opened 2022-08-22 18:21 UTC by dayZgarden

Added my own card to index.html

2022-08-22 18:22 UTC, dayZgarden commented
changes requested

2022-08-22 18:28 UTC, TenTraicion requested changes
Kindly make the recommended changes!

2022-08-22 18:28 UTC, TenTraicion commented on index.html
> +            <a href="https://www.twitter.com/" target="_blank">@zdaisygarden</a>
```suggestion
            <a href="https://www.twitter.com/zdaisygarden" target="_blank">@zdaisygarden</a>
```

2022-08-24 07:43 UTC, TenTraicion approved these changes

2022-08-24 07:43 UTC, merged

2022-08-24 07:43 UTC, TenTraicion commented
@dayZgarden, Thanks for your Contribution. and Congrats on your first PR Merge in this project. Your Card will be live within ~2-3 minutes, which can be found: [Here](https://syknapse.github.io/Contribute-To-This-Project/)!