Yushi61's Card
Syknapse/Contribute-To-This-Project pull request #1572
Opened 2022-08-30 23:15 UTC by Yushi5058

Added a new card and modified the content with my info.

2022-08-31 04:52 UTC, nzaih1999 requested changes
Hello @Yushi5058 your card is almost ready for merge but you should add comments from where the card starts to the where it ends. It helps us maintainers to and other contributors with readability. If you need any help holla me

2022-09-01 16:44 UTC, TenTraicion approved these changes

2022-09-01 16:46 UTC, merged

2022-09-01 16:46 UTC, TenTraicion commented
@Yushi5058, Thanks for your Contribution. and Congrats on your first PR Merge in this project. Your Card will be live within ~2-3 minutes, which can be found: [Here](https://syknapse.github.io/Contribute-To-This-Project/)!

2022-09-01 16:49 UTC, Yushi5058 commented
> @Yushi5058, Thanks for your Contribution. and Congrats on your first PR Merge in this project. Your Card will be live within ~2-3 minutes, which can be found: [Here](https://syknapse.github.io/Contribute-To-This-Project/)!

Thank you ☺