Added Abhishek Kumar Card
Syknapse/Contribute-To-This-Project pull request #1574
Opened 2022-08-31 15:52 UTC by abhishek44priv

2022-09-01 04:36 UTC, confused-Techie requested changes
This is looking fantastic!

I've just pointed out some things that should be addressed before this gets merged into main.

But as always thanks for your contribution!

2022-09-01 04:36 UTC, confused-Techie commented on index.html
> +                <a href="#" target="_blank" title="Second Resource">Email</a>
You'll want to make sure to change `<a href="#"` to direct to your second 'Useful Dev Resource', I saw you put 'Email' Maybe you wanted to change that to `<a href="https://mail.google.com"` or something along those lines?

2022-09-01 04:36 UTC, confused-Techie commented on index.html
> +                <a href="#" target="_blank" title="Third resource">StackOverflow</a>
Like my other comment you'll want to make sure this third 'Useful Dev Resource' points to the link you want. Likely in this case something like `<a href="https://stackoverflow.com"`.

2022-09-01 04:39 UTC, confused-Techie commented on index.html
> +          <p class="about">about you</p>
Also almost forgot, this "about you" section should tell us a little bit about yourself, feel free to refer to the [documentation](https://github.com/Syknapse/Contribute-To-This-Project#step-4-open-the-indexhtml-file) for help knowing what's expected on this section.

2022-09-04 14:51 UTC, TenTraicion approved these changes

2022-09-04 14:51 UTC, merged

2022-09-04 14:52 UTC, TenTraicion commented
@abhishek44priv, Thanks for your Contribution. and Congrats on your first PR Merge in this project. Your Card will be live within ~2-3 minutes, which can be found: [Here](https://syknapse.github.io/Contribute-To-This-Project/)!