Made requested changes
Syknapse/Contribute-To-This-Project pull request #1588
Opened 2022-09-02 12:37 UTC by Imnaseli

2022-09-02 12:52 UTC, nzaih1999 approved these changes
Hello @Imnaseli  thanks for your contribution. Will merge it real soon. Happy coding.

2022-09-02 13:32 UTC, TenTraicion requested changes
kindly do the following change and commit!

2022-09-02 13:32 UTC, TenTraicion commented on index.html
> +                    <i class="fab fa-twitter"></i>
```suggestion
                    <i class="fab fa-github"></i>
```

2022-09-03 06:09 UTC, TenTraicion commented
Hello @Imnaseli, your card has already added to the project via #1585. It can be found in [this link](https://syknapse.github.io/Contribute-To-This-Project/)!

2022-09-03 06:09 UTC, closed without merging