Working table
Syknapse/Contribute-To-This-Project pull request #1590
Opened 2022-09-02 14:09 UTC by VictorParvanov

2022-09-02 15:45 UTC, Preet-Sojitra requested changes
You have added your card at the end of the file, you are supposed to add it at the top of the file beneath the comment saying `Paste your card below this comment`. Move it upwards and then commit your changes, we will merge it.
Thank you

2022-09-02 17:53 UTC, VictorParvanov commented
Thank you! Just fixed the position of my card, but i also see that there is merge conflict now. Do i need to resolve this or the person who will make the merge. Sorry if i don't do things right, still learning it :)

2022-09-03 05:08 UTC, Preet-Sojitra approved these changes

2022-09-03 05:10 UTC, merged

2022-09-03 05:11 UTC, Preet-Sojitra commented
Congratulations @VictorParvanov  your pull request has been merged. You can view your card on [project's website](https://syknapse.github.io/Contribute-To-This-Project/). Hope you have learnt new things. 
All the best for your future journey in open source.
Have a nice day :)