dabi's card
Syknapse/Contribute-To-This-Project pull request #1616
Opened 2022-09-13 17:47 UTC by dabidabs

Added my card

2022-09-13 18:37 UTC, TenTraicion requested changes
@dabidabs, Thanks for your contribution, your card looks good. But can you move your card to the top of this section, after line 117, where it says `Paste your card directly below this line`.

2022-09-14 07:27 UTC, dabidabs commented
Done Thank you!

2022-09-14 10:51 UTC, TenTraicion approved these changes

2022-09-14 10:51 UTC, merged

2022-09-14 10:52 UTC, TenTraicion commented
@dabidabs, Thanks for your Contribution. and Congrats on your first PR Merge in this project. Your Card will be live within ~2-3 minutes, which can be found: [Here](https://syknapse.github.io/Contribute-To-This-Project/)!