New Card
Syknapse/Contribute-To-This-Project pull request #1624
Opened 2022-09-15 02:35 UTC by dquindara8

Add my card information

2022-09-15 06:03 UTC, Preet-Sojitra approved these changes
LGTM. 
Your PR will be merged soon.

2022-09-15 09:35 UTC, TenTraicion requested changes
@dquindara8, Thanks for your contribution. Kindly do the required changes and commit, it will be merged soon!

2022-09-15 09:35 UTC, TenTraicion commented on index.html
> +        <!-- ________ *TEMPLATE: MAKE A COPY* Contributor card START ________  -->
```suggestion
        <!-- ________ *Quindara* Contributor card START ________  -->
```

2022-09-15 09:35 UTC, TenTraicion commented on index.html
> +        <!-- ________*END TEMPLATE* Contributor card END ________  -->
```suggestion
        <!-- ________*Quindara* Contributor card END ________  -->
```

2022-09-16 03:48 UTC, TenTraicion approved these changes

2022-09-16 03:49 UTC, merged

2022-09-16 03:49 UTC, TenTraicion commented
@dquindara8, Thanks for your Contribution. and Congrats on your first PR Merge in this project. Your Card will be live within ~2-3 minutes, which can be found: [Here](https://syknapse.github.io/Contribute-To-This-Project/)!