Nick added a card
Syknapse/Contribute-To-This-Project pull request #1633
Opened 2022-09-16 22:00 UTC by njbernal

Added a card with my info.

2022-09-17 04:50 UTC, Preet-Sojitra requested changes
Please make suggested changes and then commit and push your changes. We will merge it after reviewing it.

2022-09-17 04:50 UTC, Preet-Sojitra commented on index.html
> +        <!-- ________ *TEMPLATE: MAKE A COPY* Contributor card START ________  -->
One should write meaningful comment so it would be great if you can change your comment to ` * Nick * Contributor card START`.

2022-09-17 04:50 UTC, Preet-Sojitra commented on index.html
> +        <!-- ________*END TEMPLATE* Contributor card END ________  -->
Also change this comment to ` * Nick * Contributor card END`.

2022-09-18 14:28 UTC, TenTraicion approved these changes

2022-09-18 14:28 UTC, merged

2022-09-18 14:29 UTC, TenTraicion commented
@njbernal, Thanks for your Contribution. and Congrats on your first PR Merge in this project. Your Card will be live within ~2-3 minutes, which can be found: [Here](https://syknapse.github.io/Contribute-To-This-Project/)!