Update index.html
Syknapse/Contribute-To-This-Project pull request #1775
Opened 2022-10-02 14:39 UTC by manasg11

2022-10-02 15:14 UTC, TenTraicion requested changes
@manasg11, move your card to the top of this section where it says `Paste Your Card Directly Below this lIne` after line 117. Follow other examples, and if need help ask away or join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF). Thanks!

2022-10-02 15:58 UTC, manasg11 commented
Hey!
I have moved it , thanks!

On Sun, 2 Oct 2022 at 20:45, TenTraicion ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> @manasg11 <https://github.com/manasg11>, move your card to the top of
> this section where it says Paste Your Card Directly Below this lIne after
> line 117. Follow other examples, and if need help ask away or join our Discord
> Server: https://discord.gg/tWkvS4ueVF <https://discord.gg/tWkvS4ueVF>.
> Thanks!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Syknapse/Contribute-To-This-Project/pull/1775#pullrequestreview-1127658514>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASSJUYKLMH3MSQ7QKJW3RM3WBGRHVANCNFSM6AAAAAAQ25YLN4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2022-10-03 14:20 UTC, TenTraicion approved these changes

2022-10-03 14:20 UTC, merged

2022-10-03 14:20 UTC, TenTraicion commented
@manasg11, Congratulation on your PR Merge, and Thanks for your Contribution. You can check your card in our [Live Website](https://syknapse.github.io/Contribute-To-This-Project/)! It may take 2-3 minutes to make your card visible in our website. 

Welcome to Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.