Added Page Scroll Up Button
Syknapse/Contribute-To-This-Project pull request #1808
Opened 2022-10-03 18:19 UTC by mgjain9871

Before:
![image](https://user-images.githubusercontent.com/71882225/193649609-4dd7a897-5f07-4c05-9fb9-3b49f8b13896.png)

After:
![image](https://user-images.githubusercontent.com/71882225/193649552-61a9ae5b-4907-4a6f-9f7c-f1e2a9de225d.png)

2022-10-03 18:19 UTC, mgjain9871 commented
Please consider it under Hacktoberfest
@Syknapse

2022-10-04 15:09 UTC, mgjain9871 commented
Hey @CandidDeer, please close the pull request with the hacktoberfest acceptes label if everything fits well.

2022-10-04 16:38 UTC, mgjain9871 commented
Hey @TenTraicion , please close this pull reques with issue #1804 with the hacktoberfest-accepted label

2022-10-04 16:42 UTC, TenTraicion commented
> Hey @TenTraicion , please close this pull reques with issue #1804 with the hacktoberfest-accepted label

@mgjain9871 kindly wait for actual reviewer. Thanks!

2022-10-06 20:41 UTC, Syknapse commented
hi @mgjain9871 thank you very much for this contribution. It really adds a good functionality and improves the website. We appreciate it. I will go ahead now and start a code review. Unfortunately, even though the button works correctly, but since the code has been copied from somewhere else you will need to do a fair bit of refactoring before we can merge it. I will let you know exactly what needs changing in the review. Thanks again for this

2022-10-06 20:57 UTC, Syknapse requested changes
Your code review is ready, please make the changes requested and we will happily merge this and tag it with hacktoberfest-accepted. Thank you

2022-10-06 20:57 UTC, Syknapse commented on assets/script.js
> +$(document).ready(function() {
You do not need the document ready block. You can remove the two functions inside of it outside and delete this line and it's corresponding closing tags

2022-10-06 20:57 UTC, Syknapse commented on assets/script.js
> +menu.onclick = () => {
This entire block needs to be deleted. `menu`is not defined and it is causing a JS error. And this block is not doing anything here. Remove it please from line 144 to 147.

2022-10-06 20:57 UTC, Syknapse commented on assets/style.css
> + padding: 21px;
Remove this padding and replace it with `width: 42px; height: 42px` which will maintain the same size but with actual dimensions and not just padding

2022-10-06 20:57 UTC, Syknapse commented on assets/style.css
> +.js .cd-top--fade-out {
You should remove all the remaining CSS you added here, from this line 32 to line 63. None of it is doing anything at all, and there are vars that aren't even declared in this project. The only thing you need from all of this section is the background in `.cd-top` which is needed for the arrow. Move it above to the main element styles `#toTopBtn`
```css
background: url(https://res.cloudinary.com/dxfq3iotg/image/upload/v1571057658/cd-top-arrow.svg) no-repeat center 50%;
```

2022-10-06 20:57 UTC, Syknapse commented on index.html
> +      <a href="#" id="toTopBtn" class="cd-top text-replace js-cd-top cd-top--is-visible cd-top--fade-out" data-abc="true"></a>
please remove all the `class` and the `data`attributes, they are not being used for anything. You need to keep only `href` and `id`

2022-11-07 16:42 UTC, TenTraicion commented
@mgjain9871, kindly make the requested changes so that we can merge your PR smoothly. for any kind of query you can ask here or in our [Discord Community: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF)

2022-11-07 17:12 UTC, Syknapse commented
Since the contrinutor has not made the changes requested but this can be a useful addition to our web, I would encourage any of our maintainers to make the requested changes themselves. This way we can merge it and benefit from this enhancement

2022-11-11 13:45 UTC, JAGDF commented
Wow I wonder how you code the scroll-up function

2022-11-23 18:34 UTC, win21H2 commented
Hello @mgjain9871,
Since we already have a scroll-to-top function on the page, I will close this PR.

Thanks, 
win21H2
324Hz

2022-11-23 18:34 UTC, closed without merging