Contributed for hacktoberfest
Syknapse/Contribute-To-This-Project pull request #1865
Opened 2022-10-05 13:23 UTC by komangss

Happy hacktoberfest! :)

2022-10-05 14:30 UTC, TenTraicion requested changes
@komangss, Kindly add 3 resources that can help developers with title, link and name. Thanks!

2022-10-07 05:41 UTC, TenTraicion commented
@komangss, Kindly follow our instruction given in our project [README.md](https://github.com/Syknapse/Contribute-To-This-Project#contribute) properly.

2022-10-07 07:50 UTC, Syknapse requested changes

2022-10-07 07:50 UTC, Syknapse commented on index.html
> +                  <a href="#" target="_blank" title="First Resource">Resource 1</a>
please provide links here in the 3 resources section

2022-10-14 06:15 UTC, TenTraicion commented
@komangss closing this.
Reason: No response. You can always make the change and reopen or create a new PR. Thanks!

for any kind of query you can ask here or in our [Discord Community: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF)

2022-10-14 06:15 UTC, closed without merging