Ahammed Imthias
Syknapse/Contribute-To-This-Project pull request #1916
Opened 2022-10-09 05:07 UTC by lalu-windows

Added my card to index.html

2022-10-09 08:05 UTC, TenTraicion requested changes
@lalu-windows, kindly do the recommended changes and commit. 

for any kind of query you can ask here or in our [Discord Community: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF)

2022-10-09 08:05 UTC, TenTraicion commented on index.html
> +        <div class="card">
```suggestion
        <!-- ________*Ahammed* Contributor card START ________ -->
        <div class="card">
```

2022-10-09 08:05 UTC, TenTraicion commented on index.html
> +        </div>
```suggestion
        </div>
        <!-- ________*Ahammed* Contributor card END ________ -->
```

2022-10-09 08:05 UTC, TenTraicion commented on index.html
> +            <a href="https://www.twitter.com/" target="https://twitter.com/LeviAckerman__l">Levi_ackerman_l</a>
```suggestion
            <a href="https://www.twitter.com/LeviAckerman__l" target="_blank">@Levi_ackerman_l</a>
```

2022-10-09 08:05 UTC, TenTraicion commented on index.html
> +          <p class="about">about you</p>
Write something about your self here...
```suggestion
          <p class="about">about you</p>
```

2022-10-09 08:05 UTC, TenTraicion commented on index.html
> +                <a href="#" target="_blank" title="First Resource">Resource 1</a>
add 3 resources that can help felow developers with a link in place of `#`, a suitable title by replacing `First Resource` and the resource name in the place where `Resource 1` is written.
```suggestion
                <a href="#" target="_blank" title="First Resource">Resource 1</a>
```

2022-10-09 08:05 UTC, TenTraicion commented on index.html
> +                <a href="#" target="_blank" title="Second Resource">Resource 2</a>
add the second resource here

2022-10-09 08:05 UTC, TenTraicion commented on index.html
> +                <a href="#" target="_blank" title="Third resource">Resource 3</a>
complete your card by adding the third resource here.

2022-10-13 08:02 UTC, TenTraicion commented
@lalu-windows, kindly do the recommended changes. The PR will be closed if we get no response within 7 days of opening. Thanks,

2022-10-17 07:11 UTC, CandidDeer commented
@lalu-windows Closing this PR now due to non-response. Please know you can create a new PR anytime and we'll be happy to merge it as long as it follows the guidelines. Thx.

2022-10-17 07:11 UTC, closed without merging