Princess's card
Syknapse/Contribute-To-This-Project pull request #1930
Opened 2022-10-10 18:55 UTC by iampearlep

Added my card to the index.html file.

2022-10-11 03:15 UTC, Michaelin007 requested changes

2022-10-11 03:15 UTC, Michaelin007 commented on index.html
> +                <a href="#" target="_blank" title="First Resource">w3Schools</a>
enter the link to those website you think as useful resoureces  and not just '#" and net naija is a movie download websites, doesn't contain any coding tools.

2022-10-11 05:18 UTC, Jagadeesh-tamizh requested changes
@iampearlep #1930  you have to all links to only useful resources instead of "#"

2022-10-12 12:17 UTC, merged

2022-10-12 12:17 UTC, CandidDeer commented
Thank you for your contribution. Your PR has been merged and your card will be live in a few moments.