made some changes from jquery to vanillajs
Syknapse/Contribute-To-This-Project pull request #1957
Opened 2022-10-14 15:25 UTC by PruthviGBhat

2022-11-07 18:01 UTC, Syknapse requested changes
This is a very nice contribution, helping us move away from jQuery. The changes requested are pretty simple, please implement them so we can merge your valuable contribution

2022-11-07 18:01 UTC, Syknapse commented on assets/script.js
> +    var event = document.createEvent('HTMLEvents');
on further examination I have just noticed that this piece of code is not doing anything in our project. Now that you are here you can have the pleasure of deleting the whole thing 😁  that's the full function called demo and it's body
```js
function demo() {
  setInterval(function() {
    $('#toggle-box-checkbox').trigger('click')
  }, 1000)
}
if (document.location.pathname.indexOf('fullcpgrid') > -1) {
  demo()
}
```

2022-11-11 11:46 UTC, TenTraicion commented
@PruthviGBhat, kindly make the requested changes so that we can merge your PR smoothly. for any kind of query you can ask here or in our [Discord Community: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF)

2022-11-14 16:55 UTC, Syknapse commented
I'm reopening because these changes are useful for our code. If @PruthviGBhat does not want to make the improvements requested for us to merge, any of us maintainers can do it and merge it so we get the benefit of this PR

2022-11-15 15:32 UTC, TenTraicion commented
Closing the PR as the updated PR is in work: #2077

2022-11-15 15:32 UTC, closed without merging