Add my card information
Syknapse/Contribute-To-This-Project pull request #1973
Opened 2022-10-18 10:14 UTC by theHabesa1

I have added resources and my card.

2022-10-18 14:10 UTC, TenTraicion requested changes
@theHabesa1, kindly add a line break before and after your card and commit. Thanks!

2022-10-22 07:54 UTC, CandidDeer commented
@theHabesa1 Kindly note that we will be closing this PR if the requested changes haven't been made 7 days after opening the PR. Thx.

2022-10-22 14:12 UTC, TenTraicion approved these changes

2022-10-22 14:13 UTC, merged

2022-10-22 14:13 UTC, TenTraicion commented
@theHabesa1, Congratulation on your PR Merge, and Thanks for your Contribution. You can check your card in our [Live Website](https://syknapse.github.io/Contribute-To-This-Project/)! It may take 2-3 minutes to make your card visible in our website. 

Welcome to Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.