Lutalo's card
Syknapse/Contribute-To-This-Project pull request #1985
Opened 2022-10-21 09:51 UTC by Bindekere

Added my card information to index.html

2022-10-21 10:54 UTC, TenTraicion requested changes
@Bindekere, Thanks for your contribution. Kindly make the recommended changes and commit. Thanks!

2022-10-21 10:54 UTC, TenTraicion commented on index.html
> +        <div class="card">
```suggestion
        <!-- ________ Bindekere card START ________ -->
        <div class="card">
```

2022-10-21 10:54 UTC, TenTraicion commented on index.html
> +            <a href="https://twitter.com/lutalo24" target="_blank">@average muganda</a>
```suggestion
            <a href="https://twitter.com/lutalo24" target="_blank">@lutalo24</a>
```

2022-10-21 10:54 UTC, TenTraicion commented on index.html
> +        </div>
```suggestion
        </div>
        <!-- ________ Bindekere card END ________ -->
```

2022-10-27 08:34 UTC, CandidDeer commented
@Bindekere Please note that open PRs with change requests will be closed 7 days after opening if the change requests have not been resolved by then. Thx.

2022-10-28 09:00 UTC, closed without merging