Marko pull request
Syknapse/Contribute-To-This-Project pull request #2007
Opened 2022-10-27 09:35 UTC by popovicmarko

2022-10-28 03:43 UTC, TenTraicion requested changes
@popovicmarko, Thanks for your contribution. Kindly make the required change and commit.

2022-10-28 03:43 UTC, TenTraicion commented on index.html
> +            <a href="https://www.twitter.com/" target="_blank">@marko_popov1c</a>
```suggestion
            <a href="https://www.twitter.com/marko_popov1c" target="_blank">@marko_popov1c</a>
```

2022-10-29 09:04 UTC, CandidDeer commented
@popovicmarko Please note that open PRs with change requests will be closed 7 days after opening if the change requests have not been resolved by then. Thx.

2022-11-02 16:57 UTC, popovicmarko reviewed
I fixed what you asked for

2022-11-02 16:57 UTC, popovicmarko commented
I've commited recommended changes

2022-11-02 18:26 UTC, TenTraicion approved these changes

2022-11-02 18:26 UTC, merged

2022-11-02 18:26 UTC, TenTraicion commented
@popovicmarko, Congratulation on your PR Merge, and Thanks for your Contribution. You can check your card in our [Live Website](https://syknapse.github.io/Contribute-To-This-Project/)! It may take 2-3 minutes to make your card visible in our website. 

Welcome to Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.