Meshack
Syknapse/Contribute-To-This-Project pull request #2060
Opened 2022-11-11 12:35 UTC by Cheberi

2022-11-11 12:40 UTC, TenTraicion requested changes
@Cheberi, Undo the CSS file and do the mentioned changes in your card. Thanks!

2022-11-11 12:40 UTC, TenTraicion commented on index.html
> +   <!-- ________ *TEMPLATE: MAKE A COPY* Contributor card START ________  -->
```suggestion
   <!-- ________ *Meshack Cheberi* Contributor card START ________  -->
```

2022-11-11 12:40 UTC, TenTraicion commented on index.html
> +      <a href="https://www.linkedin.com/in/meshack-cheberi-530a2a220/" target="_blank">LinkedIn</a>
```suggestion
      <a href="https://www.linkedin.com/in/meshack-cheberi-530a2a220/" target="_blank">@meshack-cheberi</a>
```

2022-11-11 12:40 UTC, TenTraicion commented on index.html
> +      <a href="https://github.com/Cheberi" target="_blank">Github</a>
```suggestion
      <a href="https://github.com/Cheberi" target="_blank">@Cheberi</a>
```

2022-11-11 12:40 UTC, TenTraicion commented on index.html
> +  <!-- ________ *END TEMPLATE* Contributor card END ________  -->
```suggestion
  <!-- ________ *Meshack Cheberi* Contributor card END ________  -->
```

2022-11-14 07:18 UTC, CandidDeer commented
@Cheberi Please note that we will be closing this PR 7 days after opening if the requested changes haven't been made by then. Please feel free to reach out if you have any questions. Thx.

2022-11-14 16:36 UTC, merged

2022-11-14 16:37 UTC, TenTraicion commented
@Cheberi, Congratulation on your PR Merge, and Thanks for your Contribution. You can check your card in our [Live Website](https://syknapse.github.io/Contribute-To-This-Project/)! It may take 2-3 minutes to make your card visible in our website. 

Welcome to Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.