Update : Allen
Syknapse/Contribute-To-This-Project pull request #2122
Opened 2022-11-25 14:19 UTC by AllenP3

added AllenP's card

2022-11-25 14:47 UTC, TenTraicion requested changes
@AllenP3, fix your card by following the given suggestions. Thanks!

2022-11-25 14:47 UTC, TenTraicion commented on index.html
> +                <a href="#" target="https://www.w3schools.com/" title="Third resource">W3schools</a>
```suggestion
                <a href="https://www.youtube.com/@freecodecamp" target="_blank" title="Second Resource">Freecodecamp</a>
              </li>
              <li>
                <a href="https://www.w3schools.com/" target="_blank" title="Third resource">W3schools</a>
```

2022-11-29 07:48 UTC, CandidDeer commented
@AllenP3 Please note that we will be closing this PR 7 days after the initial opening if the requested changes have not been resolved by then. Please always feel free to reach out if you have any questions on how to resolve. Thx.

2022-12-01 15:17 UTC, TenTraicion approved these changes

2022-12-01 15:18 UTC, merged

2022-12-01 15:18 UTC, TenTraicion commented
@AllenP3, Congratulation on your PR Merge, and Thanks for your Contribution. You can check your card in our [Live Website](https://syknapse.github.io/Contribute-To-This-Project/)! It may take 2-3 minutes to make your card visible in our website. 

Welcome to Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.