saurabh damle's card
Syknapse/Contribute-To-This-Project pull request #2231
Opened 2022-12-30 19:40 UTC by saurabhdamle11

added my card to index.html

2022-12-31 05:07 UTC, Michaelin007 requested changes

2022-12-31 05:07 UTC, Michaelin007 commented on index.html
> +        <div class="card">
Hi, your card is missing the opening and the ending comment. Card Start and card end. Check the template as a guide.
Thanks

2023-01-01 11:51 UTC, CandidDeer approved these changes

2023-01-01 11:51 UTC, merged

2023-01-01 11:52 UTC, CandidDeer commented
Thank you for your contribution and making the requested changes. I have merged your PR and your card will be live in a moment.