added new card
Syknapse/Contribute-To-This-Project pull request #2238
Opened 2023-01-01 14:44 UTC by Datcyx

2023-01-02 06:20 UTC, TenTraicion requested changes
@Datcyx , kindly make the requested changes and commit. Thanks!

2023-01-02 06:20 UTC, TenTraicion commented on index.html
> +            <a href="https://www.twitter.com/" target="#">None</a>
Replace username with your twitter username. if you don't have twitter replace twitter in this line and the line before with github and, replace the username with your github username. 
```suggestion
            <a href="https://www.twitter.com/username" target="_blank">@username</a>

```

2023-01-02 06:20 UTC, TenTraicion commented on index.html
> +                <a href="#" target="https://itsourcecode.com/" title="IT source code">ITsourceCode(A totorial website of my IT Teacher)</a>
```suggestion
                <a href="https://www.w3schools.com/" target="_blank" title="W3schools">Web Development for beginner(W3schools)</a>
              </li>
              <li>
                <a href="https://education.github.com/pack/offers" target="_blank" title="Github Student">Have Your Cloud Server by Applying on Github Student Pack</a>
              </li>
              <li>
                <a href="https://itsourcecode.com/" target="_blank" title="IT source code">ITsourceCode(A totorial website of my IT Teacher)</a>

```

2023-01-02 07:42 UTC, Datcyx commented
I'm sorry, I don't notice my wrong, I have a bad day when I did this

2023-01-02 16:40 UTC, TenTraicion commented
> I'm sorry, I don't notice my wrong, I have a bad day when I did this

@Datcyx, No sweat, but you still need to fix your twitter handel.

2023-01-03 11:17 UTC, Datcyx commented
I don't have twitgee

2023-01-03 11:30 UTC, Datcyx commented
Hi I updated my twitter now

2023-01-03 17:12 UTC, TenTraicion approved these changes

2023-01-03 17:14 UTC, merged

2023-01-03 17:15 UTC, TenTraicion commented
@Datcyx, Congratulation on your PR Merge, and Thanks for your Contribution. You can check your card in our [Live Website](https://syknapse.github.io/Contribute-To-This-Project/)! It may take 2-3 minutes to make your card visible in our website. 

Welcome to Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.