Add my card information
Syknapse/Contribute-To-This-Project pull request #2273
Opened 2023-01-14 23:54 UTC by rcDeveloping

Added my  card information to index.html file.

2023-01-15 08:36 UTC, CandidDeer requested changes
Please note you are not allowed to make changes to the template directly. Instead, copy the template, paste it in line 117 and fill it in there. Once this change request has been resolved, I'll be happy to merge. Thx.

2023-01-15 20:30 UTC, rcDeveloping reviewed
Retified my card information.

2023-01-16 07:42 UTC, CandidDeer approved these changes

2023-01-16 07:44 UTC, merged

2023-01-16 07:45 UTC, CandidDeer commented
Thank you for your contribution and making the requested changes. I have merged your PR and your card will be live in a moment.