add my card information
Syknapse/Contribute-To-This-Project pull request #2380
Opened 2023-02-27 16:19 UTC by arnab9593

all information added

2023-02-27 20:31 UTC, alsonick requested changes
Can you update this comment with your name instead, thanks.

2023-02-27 20:31 UTC, alsonick commented on index.html
> +        <!-- ________ Marek card END ________  -->
This comment should include your name.

2023-02-28 05:42 UTC, arnab9593 commented on index.html
> +        <!-- ________ Marek card END ________  -->
changes done

2023-02-28 07:24 UTC, CandidDeer approved these changes

2023-02-28 07:24 UTC, merged

2023-02-28 07:24 UTC, CandidDeer commented
Thanks for your contribution. I have merged your PR and your card will be live in a moment.