updated hindi readme.md
Syknapse/Contribute-To-This-Project pull request #2439
Opened 2023-03-26 03:08 UTC by DhruvMishra1826

@akkshayTandon i have updated some links and images which were not working earlier. Please review it.

2023-03-26 09:21 UTC, CandidDeer commented
@Syknapse Please review this general enhancement and let me know whether I should merge. Thx.

2023-03-30 12:42 UTC, DhruvMishra1826 commented
> * on line no. 101,  the image is not showing
> 
>     * on line no. 287, the link is broken

Ok, i will update that.

2023-04-03 18:29 UTC, TenTraicion requested changes
@DhruvMishra1826, maybe this will do the trick, also about Line 287, removing space in the link will fix it. `https:/  /`

2023-04-03 18:29 UTC, TenTraicion commented on translations/README/HINDI.md
> +| <ul><li>_File_ पर क्लिक करें, फिर _Clone रिपॉजिटरी_</li></ul> | पर क्लिक करें ![क्लोन](/readme-only/clone.पीएनजी 'क्लिक क्लोन रिपॉजिटरी') |
```suggestion
| <ul><li>_File_ पर क्लिक करें, फिर _Clone रिपॉजिटरी_</li></ul> | पर क्लिक करें ![क्लोन](/readme-only/clone "पीएनजी 'क्लिक क्लोन रिपॉजिटरी'") |
```

2023-04-04 14:41 UTC, Syknapse commented
> @Syknapse Please review this general enhancement and let me know whether I should merge. Thx.

Once the changes requested are done, we can go ahead and merge, thank you

2023-04-04 17:51 UTC, TenTraicion approved these changes

2023-04-04 17:52 UTC, merged

2023-04-04 17:52 UTC, TenTraicion commented
@DhruvMishra1826, Congratulation on your PR Merge, and Thanks for your Contribution. You can check your card in our [Live Website](https://syknapse.github.io/Contribute-To-This-Project/)! It may take 2-3 minutes to make your card visible in our website. 

Welcome to Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.