verxckterq's Card
Syknapse/Contribute-To-This-Project pull request #2460
Opened 2023-04-01 10:32 UTC by verxckterq

Added my card to index.html.

2023-04-02 07:52 UTC, CandidDeer requested changes
Please add your twitter handle (ar alternatively another Social media profile) to your card. Please also replace the "<!-- ________ *TEMPLATE: MAKE A COPY* Contributor card START ________  -->" with "<!-- ________ "your name" card START ________  --> and do the same with the card end comment.
Also, please note that we will be closing any PRs with unresolved change requests 7 days after the intial PR opening date. Feel free to reach out if you have questions. Thx.

2023-04-04 18:04 UTC, TenTraicion approved these changes

2023-04-05 06:18 UTC, CandidDeer approved these changes

2023-04-05 06:19 UTC, CandidDeer commented
Thank you for your contribution and making the requested changes. I have merged your PR and your card will be live in a moment.

2023-04-05 06:19 UTC, merged