Add Grxypth Card Info
Syknapse/Contribute-To-This-Project pull request #2553
Opened 2023-05-02 17:42 UTC by Grxypth

Added a new card and modified the content with my info

2023-05-03 06:04 UTC, CandidDeer requested changes
Please move your card up to start in line 117 to follow our instructions. Thx.

2023-05-04 07:02 UTC, CandidDeer approved these changes

2023-05-04 07:02 UTC, merged

2023-05-04 07:02 UTC, CandidDeer commented
Looks good now, thx! Merged! 👍🏻

2023-05-04 18:32 UTC, Grxypth commented
You're welcome