Update index.html
Syknapse/Contribute-To-This-Project pull request #2565
Opened 2023-05-08 10:47 UTC by ArieCrespine

add my card descriprion

2023-05-08 18:56 UTC, alsonick requested changes
Please replace the text in asterisks (`*`) with either your name or username. Also, can you fix the indentation on line 118? Thanks

2023-05-09 05:58 UTC, CandidDeer approved these changes

2023-05-09 05:58 UTC, merged

2023-05-09 05:58 UTC, CandidDeer commented
Thank you for your contribution. I have merged your PR and your card will be live in a moment.

2023-05-09 09:17 UTC, ArieCrespine commented
Thank you, it was a pleasure!
Best regards

Le mar. 9 mai 2023 à 12:11, Lisa Thamer ***@***.***> a écrit :

> Thank you for your contribution. I have merged your PR and your card will
> be live in a moment.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Syknapse/Contribute-To-This-Project/pull/2565#issuecomment-1539456020>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJQRRMAUZZOO76ASTNPEW23XFIC5ZANCNFSM6AAAAAAXZYUJ2M>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>