added my card
Syknapse/Contribute-To-This-Project pull request #2582
Opened 2023-05-13 13:42 UTC by StefanBeh

2023-05-14 07:26 UTC, CandidDeer requested changes
Instead of a blank twitter contact, please provide alternative social media account(s) - you could even provide your github account if you have no social media at all. Thx.

2023-05-14 08:01 UTC, StefanBeh commented
Thanks for the review. I've added my LinkedIn profile.

2023-05-15 07:42 UTC, CandidDeer approved these changes

2023-05-15 07:42 UTC, merged

2023-05-15 07:43 UTC, CandidDeer commented
Thank you for your contribution and making the requested changes. I have merged your PR and your card will be live in a moment.