Add Simona card
Syknapse/Contribute-To-This-Project pull request #2590
Opened 2023-05-16 15:21 UTC by SimonaPiz

Add my card in index.html

2023-05-16 20:57 UTC, alsonick requested changes
Please replace the `*TEMPLATE*` text with either your name or username. Thanks

2023-05-17 08:09 UTC, SimonaPiz commented
@alsonick  
> Please replace the `*TEMPLATE*` text with either your name or username. Thanks

I have replace it with my name. 👍

2023-05-17 15:33 UTC, alsonick requested changes
You need to replace the `*TEMPLATE*` text on line 140, please undo the changes you've made on line 108. Thanks

2023-05-18 12:50 UTC, alsonick requested changes

2023-05-18 12:50 UTC, alsonick commented on index.html
> +          <!-- ________ Simona Pizio Contributor card END ________  -->
Please undo the changes on line 108.

2023-05-20 07:20 UTC, CandidDeer approved these changes

2023-05-20 07:20 UTC, merged

2023-05-20 07:20 UTC, CandidDeer commented
Thank you for your contribution. I have merged your PR and your card will be live in a moment.