Arsh's card
Syknapse/Contribute-To-This-Project pull request #2636
Opened 2023-05-31 13:53 UTC by Lazerx2reem

added a card of Arsh Gupta

2023-05-31 14:25 UTC, TenTraicion requested changes
@Lazerx2reem, kindly add your instagram handle with a valid profile link, and add 2 more usefull resources for programmers/ web devs. Thanks!

2023-06-04 06:30 UTC, CandidDeer commented
@Lazerx2reem Please note that any PRs with unresolved change requests will be closed 7 days after initial opening. Thx.

2023-06-04 18:18 UTC, TenTraicion approved these changes

2023-06-04 18:21 UTC, merged

2023-06-04 18:21 UTC, TenTraicion commented
@Lazerx2reem, Congratulation on your PR Merge, and Thanks for your Contribution. You can check your card in our [Live Website](https://syknapse.github.io/Contribute-To-This-Project/)! It may take 2-3 minutes to make your card visible in our website. 

Welcome to Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.