I add my own card with my informations
Syknapse/Contribute-To-This-Project pull request #2662
Opened 2023-06-15 16:24 UTC by Jasper-Claus

In dieser PR geht es darum das ich meine eigene karte hinzugefügt habe.

2023-06-15 17:15 UTC, CandidDeer requested changes
Please move your card up to start from line 117 to follow our guidelines. Thx.

2023-06-16 05:19 UTC, TenTraicion approved these changes

2023-06-16 05:44 UTC, CandidDeer approved these changes

2023-06-16 05:44 UTC, merged

2023-06-16 05:44 UTC, CandidDeer commented
Thank you for making the requested changes. I have merged your PR now and it will be live in a moment.