Add Ignatius-K card info
Syknapse/Contribute-To-This-Project pull request #2663
Opened 2023-06-17 07:16 UTC by Ignatius-K

Adding my card, just contributing to software

- [x] Read the guidelines
- [x] Added the card
- [x] Cross-checked if I met the guidelines

2023-06-17 07:20 UTC, CandidDeer requested changes
Thank you for your contribution. Please move your card up to start in line 117. Thx.

2023-06-17 10:06 UTC, Ignatius-K commented
I have made another commit.

Am inquiring if I make another commit, is there need to message the maintainers of the project or they shall be notified by Github ?

**Thank you.**

2023-06-17 12:44 UTC, TenTraicion approved these changes

2023-06-17 19:48 UTC, alsonick approved these changes

2023-06-18 06:52 UTC, CandidDeer approved these changes

2023-06-18 09:45 UTC, closed without merging