Update index.html
Syknapse/Contribute-To-This-Project pull request #2698
Opened 2023-07-04 07:48 UTC by luisv01

!

2023-07-04 07:59 UTC, luisv01 commented
!

2023-07-04 09:43 UTC, TenTraicion requested changes
@luisv01, you need to add your social handle in the code.

2023-07-04 09:43 UTC, TenTraicion commented on index.html
> +                <a href="https://github.com/luisv01" target="_blank">Your handle</a>
```suggestion
                <a href="https://github.com/luisv01" target="_blank">@luisv01</a>
```

2023-07-04 21:14 UTC, luisv01 commented
> @luisv01, you need to add your social handle in the code.

@TenTraicion thanks for catching that. Applied your suggestion!

2023-07-04 21:16 UTC, luisv01 reviewed
@TenTraicion all set, thanks for the comment!

2023-07-05 04:37 UTC, TenTraicion approved these changes

2023-07-05 04:37 UTC, merged

2023-07-05 04:38 UTC, TenTraicion commented
@luisv01, Congratulation on your PR Merge, and Thanks for your Contribution. You can check your card in our [Live Website](https://syknapse.github.io/Contribute-To-This-Project/)! It may take 2-3 minutes to make your card visible in our website. 

Welcome to Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.