Created my card
Syknapse/Contribute-To-This-Project pull request #2766
Opened 2023-07-26 13:50 UTC by TheJSPythonator

I created my card.

2023-07-27 17:00 UTC, CandidDeer requested changes
Please add a social media handle. This can bei any Platform, even your GitHub. Thx.

2023-07-30 08:31 UTC, TheJSPythonator commented
Ok!

2023-07-30 13:10 UTC, TenTraicion requested changes
@TheJSPythonator,
Kindly make the following changes, so that we can merge your card. Thanks..!

2023-07-30 13:10 UTC, TenTraicion commented on index.html
> +            <a href="https://github.com/TheJSPythonator" target="_blank">Github</a>-->
```suggestion
            <a href="https://github.com/TheJSPythonator" target="_blank">@TheJSPythonator</a>
```

2023-07-30 13:10 UTC, TenTraicion commented on index.html
> +                <a href="https://developer.mozilla.org/en-US/" title="MDN Web Docs">MDN Web Docs</a>/a>/a>/a>/a>a>
```suggestion
                <a href="https://developer.mozilla.org/en-US/" title="MDN Web Docs">MDN Web Docs</a>
```

2023-07-30 13:10 UTC, TenTraicion commented on index.html
>           <!-- ========= Start ========= -->
move your card after this line where it says, Start
make sure your card has a line break after and before.

2023-08-02 10:14 UTC, closed without merging