hamza's card
Syknapse/Contribute-To-This-Project pull request #2780
Opened 2023-08-02 09:34 UTC by Hamza6-hash

just added my information to the card

2023-08-02 10:19 UTC, CandidDeer requested changes
Please add your handles to your Twitter and Github hrefs.

2023-08-02 15:56 UTC, Hamza6-hash commented
> Please add your handles to your Twitter and Github hrefs.

Thanks it's done can you check if it's working or not...

2023-08-03 05:00 UTC, CandidDeer approved these changes

2023-08-03 05:00 UTC, merged

2023-08-03 05:01 UTC, CandidDeer commented
Well done! Thank you for your contribution. I have merged your PR and your card will be live in a moment.