Brendan's Card
Syknapse/Contribute-To-This-Project pull request #2814
Opened 2023-08-15 07:31 UTC by BrendanFre

Added a new card with my details.

2023-08-15 07:54 UTC, CandidDeer requested changes
Please add your dedicated twitter and github handles to each href. Please also replace "TEMPLATE: MAKE A COPY" with your name in both the start and end comments. Thx.

2023-08-15 11:53 UTC, BrendanFre commented
Added name to the template heading. Also checked twitter and github links.

2023-08-16 06:03 UTC, CandidDeer approved these changes

2023-08-16 06:04 UTC, merged

2023-08-16 06:04 UTC, CandidDeer commented
Thank you for your contribution. I have merged your PR and your card will be live in a moment.