Add Traditional Chinese README.md
Syknapse/Contribute-To-This-Project pull request #2873
Opened 2023-08-29 10:01 UTC by ascodeasice

2023-08-29 14:12 UTC, TenTraicion requested changes
@ascodeasice, looks fine to me. But i will recommend some changes:
1. Change the file name to: `CHINESE.trad.md` || `CHINESE.traditional.md` (i prefer the shortest one though)
2. Input in the language table alphabetically. (Optional)

Thanks for all the hard work. and we are looking forward to more contributions of your.

-Regards

2023-08-30 03:03 UTC, ascodeasice commented
Hi, I used Chinese (Traditional) in table since there's sorting

2023-08-30 17:11 UTC, TenTraicion requested changes
@ascodeasice, need some more changes, mentioned below:

2023-08-30 17:11 UTC, TenTraicion commented on README.md
>  | [Portuguese](/translations/README/PORTUGUESE.md) | [Russian](/translations/README/RUSSIAN.md) |  [Serbian](/translations/README/SERBIAN.md)  | [Spanish](/translations/README/SPANISH.md) | [Turkish]
Polish is missing

2023-08-30 17:11 UTC, TenTraicion commented on translations/translation.md
>  | [Portuguese](README/PORTUGUESE.md) | [Russian](README/RUSSIAN.md) | [Serbian](README/SERBIAN.md)   | [Spanish](README/SPANISH.md) | [Turkish](README/TURKISH.md) |
Polish is missing

2023-08-30 17:11 UTC, TenTraicion commented on translations/translation.md
>  | [Ukrainian](README/UKRAINIAN.md) |
```suggestion
| [German](README/German.md) | [Hindi](README/HINDI.md)   | [Italian](README/ITALIAN.md) | [Japanese](README/JAPANESE.md) | [Korean](README/KOREAN.md)   | 
| [Polish](README/POLISH.md) | [Portuguese](README/PORTUGUESE.md) | [Russian](README/RUSSIAN.md) | [Serbian](README/SERBIAN.md)   | [Spanish](README/SPANISH.md) |
| [Turkish](README/TURKISH.md) | [Ukrainian](README/UKRAINIAN.md) |
```

2023-08-31 02:48 UTC, ascodeasice commented
Done, thanks for reminding!

2023-08-31 14:24 UTC, TenTraicion approved these changes

2023-08-31 14:24 UTC, merged

2023-08-31 14:27 UTC, TenTraicion commented
@ascodeasice, Congratulation on your PR Merge, and Thanks for your Contribution. Don't forget to add your card in our project. Looking forward to your future contributions.

Welcome to Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.