set
Syknapse/Contribute-To-This-Project pull request #2879
Opened 2023-08-31 11:45 UTC by KaranRaval555

2023-09-01 07:24 UTC, CandidDeer requested changes
Please note you are not supposed to fill in the template directly. Instead, copy and paste the template below and fill it in there. Thx.

2023-09-01 15:02 UTC, KaranRaval123 commented
What do you mean by 'paste it'? I followed all of the instructions. Can you elaborate more? I don't understand

2023-09-02 06:27 UTC, CandidDeer commented
You need to copy lines 76 to 101, move your cursor into line 111, paste there and then fill it in there.

2023-09-03 11:24 UTC, KaranRaval123 commented on index.html
I'm sorry for the misunderstanding. I committed multiple times due to some issues because GitHub wasn't capturing recent changes. Please accept my card information. Thanks!

2023-09-03 15:20 UTC, KaranRaval123 commented
I know it's my fault, but why am I struggling this much? The code was different from what I pushed through GitHub Desktop

2023-09-03 20:57 UTC, Syknapse commented
> I know it's my fault, but why am I struggling this much? The code was different from what I pushed through GitHub Desktop

Don't worry, it can always be confusing when learning to do this the first time. You'll eventually get used to it and find it easier. From what I can see your PR now is looking good. One of the maintainers will review it soon and let you know. Keep going!

2023-09-04 07:21 UTC, CandidDeer approved these changes

2023-09-04 07:21 UTC, merged

2023-09-04 07:22 UTC, CandidDeer commented
Thank you for your contribution. I have merged your PR and your card will be live in a moment.