Updated Swahili README
Syknapse/Contribute-To-This-Project pull request #3117
Opened 2023-10-10 18:28 UTC by fvaysh

Issue Number - #3017 

I have taken time to process each part one by one and modified and improved it as per the conditions you mentioned.
Please check it and merge it.

In this commit, I have significantly improved the clarity and comprehensibility of the Swahili instructions. 
I made sure that the instructions are crystal clear. Users should now find it easier to understand and follow the guidelines provided.
I making improvements, we carefully maintained the original style and tone of the instructions. This ensures that the code has not been changed too much and it matched it with your original English ReadME file.
I fixed typos and grammar issues to ensure the instructions are error-free.

2023-10-11 05:53 UTC, CandidDeer commented
@Syknapse Please let me know if we can merge this. Thx.

2023-10-12 17:00 UTC, fvaysh commented
> @Syknapse Please let me know if we can merge this. Thx.

Can I please have the update on this, I already have checked for cases and improved it properly. So, can you please see if it can be merged?

2023-10-13 17:48 UTC, fvaysh commented
@Syknapse heya, sorry to disturb, but can you merge this if everything works fine, I fixed up typos, improved clarity, and took me time for this, can you please check and merge it ?

2023-10-21 16:55 UTC, TenTraicion requested changes
@fvaysh Thanks for your contribution, k9indly make those changes, and mention me after the changes.

2023-10-21 16:55 UTC, TenTraicion commented on translations/README/SWAHILI.md
> +[![Open Source Love](https://badges.frapsoft.com/os/v2/open-source.svg?v=103)](https://syknapse.github.io/Changia-Kwa-Hii-Mradi/)
the links shouldn't be translated. kindly reverse this and change it to same as original README file (english)

2023-10-21 16:55 UTC, TenTraicion commented on translations/README/SWAHILI.md
> +- **Asante kwa kuchangia mradi huu**. Sasa unaweza kuendelea na kujaribu kuchangia miradi mingine; tafuta ![Toleo zuri la Kwanza](https://user-images.githubusercontent.com/29199184/33852733-e23b70 70
again the links shoudn't be changed in any circumstances. they should be same as original README (eng)

2023-10-29 02:05 UTC, closed without merging