Create maintainer_guide.spa.md
Syknapse/Contribute-To-This-Project pull request #3140
Opened 2023-10-12 05:53 UTC by Harshayu

added Spanish translation

2023-10-12 07:21 UTC, CandidDeer commented
@Syknapse Please let me know if we can merge this. Thx.

2023-10-14 07:03 UTC, Harshayu commented
@Syknapse is there any changes needed ?
 if everything is ok then pls merge it

2023-10-21 17:24 UTC, TenTraicion requested changes
@Harshayu, Thanks for your contribution. kindly make the required change and we are good to go.

2023-10-21 17:24 UTC, TenTraicion commented on translations/maintainer_guide/maintainer_guide.spa.md
> +  Las traducciones para la documentación de proyectos son bienvenidas. Lee la [`Guía de Traducción`]
the link isn't working, kindly remove the space/line break to make that work.

2023-10-21 17:24 UTC, TenTraicion commented on translations/maintainer_guide/maintainer_guide.spa.md
> +  (translations/README.md)para contribuir."
```suggestion
  Las traducciones para la documentación de proyectos son bienvenidas. Lee la [`Guía de Traducción`](translations/README.md) para contribuir."
```

2023-10-29 02:05 UTC, closed without merging