Create maintainer_guide.french.md
Syknapse/Contribute-To-This-Project pull request #3258
Opened 2023-10-21 11:24 UTC by kushal34712

converted plz accpet it

2023-10-21 17:33 UTC, kushal34712 commented
@ascodeasice what more chanage i need to do ?

2023-10-21 17:39 UTC, kushal34712 commented
sir just accpet it then as per preview and all i will make changes in it

2023-10-21 17:51 UTC, TenTraicion requested changes
@kushal34712, kindly make the requested changes. Thanks

2023-10-21 17:51 UTC, TenTraicion commented on translations/maintainer_guide/maintainer_guide.french.md
file naming is incorrect

2023-10-21 17:51 UTC, TenTraicion commented on translations/maintainer_guide/maintainer_guide.french.md
> +
what is this for?

2023-10-22 05:36 UTC, kushal34712 commented
@TenTraicion ##Merci = thank you

2023-10-22 05:40 UTC, kushal34712 commented
i have made all the changes check it out

2023-10-22 07:22 UTC, TenTraicion requested changes
@kushal34712, still need some changes mentioned below:

2023-10-22 07:22 UTC, TenTraicion commented on translations/maintainer_guide/maintainer_guide.french.md
> +> Les traductions des documentations de projets sont les bienvenues. Lire [`Guide de traduction`](translations/README.md)contribuer.
broken links

2023-10-22 07:22 UTC, TenTraicion commented on translations/maintainer_guide/maintainer_guide.french.md
> +```
don't translate the codes

2023-10-22 07:22 UTC, TenTraicion commented on translations/maintainer_guide/maintainer_guide.french.md
file name should be `maintainer_guide.fra.md`
kindly change the file name.

2023-10-22 07:22 UTC, TenTraicion commented
you may follow other translations to fix the links. Thanks

2023-10-25 09:31 UTC, kushal34712 commented
i have made update con u check

2023-10-25 09:49 UTC, kushal34712 commented
@TenTraicion all links are working just check it once

2023-10-25 16:59 UTC, TenTraicion requested changes

2023-10-25 16:59 UTC, TenTraicion commented on translations/maintainer_guide/maintainer_guide.fra.md
> +
```suggestion
[![Discord](https://badgen.net/discord/online-members/tWkvS4ueVF?label=Join%20Our%20Discord%20Server&icon=discord)](https://discord.gg/tWkvS4ueVF 'Join our Discord server!')
```

2023-10-25 16:59 UTC, TenTraicion commented on translations/maintainer_guide/maintainer_guide.fra.md
> +npx plus joli --write index.html
```suggestion
npx prettier --write index.html
```

2023-10-25 16:59 UTC, TenTraicion commented on translations/maintainer_guide/maintainer_guide.fra.md
> +- Vérifiez ensuite tout conflit. Fusionnez « master » dans la branche PR pour résoudre les conflits. Les conflits surviennent généralement lorsqu'un certain temps s'est écoulé depuis les fusions préc
```suggestion
- Vérifiez ensuite tout conflit. Fusionnez `master` dans la branche PR pour résoudre les conflits. Les conflits surviennent généralement lorsqu'un certain temps s'est écoulé depuis les fusions précédentes et que plusieurs PR utilisent la même version obsolète.
```

2023-10-25 16:59 UTC, TenTraicion commented on translations/maintainer_guide/maintainer_guide.fra.md
> +> Les traductions des documentations de projets sont les bienvenues. Lire [`Guide de traduction`](https://github.com/Syknapse/Contribute-To-This-Project/blob/69f692fc596e46dfe624e3d263b458defd31b258/
```suggestion
> Les traductions des documentations de projets sont les bienvenues. Lire [`Guide de traduction`](../README.md) contribuer.
```

2023-10-25 17:00 UTC, kushal34712 commented
@TenTraicion have u checked

2023-10-25 17:00 UTC, merged

2023-10-26 00:13 UTC, kushal34712 commented
Sir the changes can u re open it and mere it bcz it is not reflecting in my account