Create maintainer_guide.mar.md
Syknapse/Contribute-To-This-Project pull request #3264
Opened 2023-10-21 16:18 UTC by SoulNikhar

maintainer guide in Marathi translation

2023-10-21 17:54 UTC, TenTraicion requested changes
@SoulNikhar, Thanks for your contribution. Kindly fix the links. They seem wrong.

2023-10-21 18:17 UTC, SoulNikhar commented
Hii ... @TenTraicion  
Now all the links are fixed. Please have a look.

2023-10-22 07:17 UTC, TenTraicion requested changes
Still, some links are broken.. kindly follow other translations for that. Thanks!

2023-10-22 14:58 UTC, SoulNikhar commented
> Still, some links are broken.. kindly follow other translations for that. Thanks!

Sorry @TenTraicion, I followed maintainer_guide.hin.md and checked all the links from my side. If there are still any broken links, please provide me with screenshots so that I can look into it.

2023-10-22 15:33 UTC, TenTraicion approved these changes

2023-10-22 15:33 UTC, TenTraicion commented on translations/maintainer_guide/maintainer_guide.mar.md
> +हे ट्यूटोरियल उपलब्ध आहे [इतर भाषांमध्ये](translation/README.md)
```suggestion
हे ट्यूटोरियल उपलब्ध आहे [इतर भाषांमध्ये](/translation/README.md)
```

2023-10-22 15:33 UTC, TenTraicion commented
fixed and merged*

2023-10-22 15:33 UTC, merged