[ADDED]: Killer2OP
Syknapse/Contribute-To-This-Project pull request #3311
Opened 2023-10-24 11:52 UTC by Killer2OP

# Description
Added 2 python resources and also have added my name

2023-10-25 06:49 UTC, CandidDeer requested changes
Please add a third useful resource. Thx.

2023-10-25 07:27 UTC, Killer2OP commented
> Please add a third useful resource. Thx.

DONE. @CandidDeer

2023-10-26 05:30 UTC, CandidDeer approved these changes

2023-10-26 05:30 UTC, merged

2023-10-26 05:30 UTC, CandidDeer commented
Thank you for your contribution. I have merged your PR and your card will be live in a moment.