Chase Corbitt's card
Syknapse/Contribute-To-This-Project pull request #3430
Opened 2023-12-12 18:19 UTC by metaltheory

Added my card to the index.html file.

2023-12-13 06:35 UTC, CandidDeer requested changes
Your commit is trying to change all 1.2+ lines of code. This should not happen. Please note there's no need to touch (or even format) any code outside of your new card. Can you please fix your commit and push again? Thx.

2023-12-13 16:16 UTC, metaltheory commented
I think my commit here should have fixed it. I believe I used the hotkey to format the document and that caused the issue. I reverted it back to the original formatting.

2023-12-14 07:43 UTC, CandidDeer approved these changes

2023-12-14 07:43 UTC, merged

2023-12-14 07:44 UTC, CandidDeer commented
Thank you for fixing it, yes, it worked. I have merged your PR now and your card will be live in a moment.