Adam Magyar's card
Syknapse/Contribute-To-This-Project pull request #3492
Opened 2024-01-11 17:06 UTC by Adam3306

2024-01-11 22:14 UTC, Amazening requested changes
Hey Adam, great work on your pull request. There's just one small mistake to fix before we merge.

Your card should ideally be added below the line that says `<!-- ========= Paste YOUR CARD directly BELOW this line ========= -->`

That is to say, the code you wrote from lines 119 to 146 should be moved to be after what is currently line 151.



This is important to maintain cleanliness and clarity, especially for future contributors.


Please adjust this, and then I'll review your pull request again and merge. Thank you for your contribution!

2024-01-12 12:11 UTC, Adam3306 commented
Dear [Amazening](https://github.com/Amazening),

I have made the requested changes, apologise for the concerns.

Best,
Adam

2024-01-13 17:24 UTC, TenTraicion approved these changes

2024-01-16 15:20 UTC, merged

2024-01-16 15:21 UTC, TenTraicion commented
@Adam3306Congratulations on your PR Merge, and Thanks for your Contribution. You can check your card on our [Live Website](https://syknapse.github.io/Contribute-To-This-Project/)! It may take 2-3 minutes to make your card visible on our website. 

Welcome to the Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.