SWAHILI.md file Translation.
Syknapse/Contribute-To-This-Project pull request #3506
Opened 2024-01-16 12:44 UTC by the1Riddle

hello @TenTraicion and @Syknapse
 
As it was mentioned in the issue #3017
i made the needed improvements on the `SWAHILI.md` file working on the format which was a problem in it.
some sections are also made to align with the recently updated readme file on the main repo's master branch.

just to mention an example is the [quick access section](https://github.com/Syknapse/Contribute-To-This-Project#quick-access-index)

hope it meets your satisfaction, and will be merged soon, if there is any part that would need to be edited, 
i would be ready to do so. 

address #3017 , thanks.

2024-01-16 13:08 UTC, the1Riddle commented
address #2826

2024-01-16 13:44 UTC, waynemorphic commented on translations/README/SWAHILI.md
> +| :arrow_right_hook: Mradi uliogawiwa utakuwa na ishara ya kugawanywa kushoto. Gawanya lako litakuwa na mtumiaji wako wa GitHub yenyewe. | ![your fork](/readme-only/clone-your-fork.PNG 'your fork wil
Gawanyo lako litakuwa -> mgawanyo wako utakuwa

2024-01-16 14:01 UTC, the1Riddle commented on translations/README/SWAHILI.md
> +[![Upendo wa Chanzo Wazi](https://badges.frapsoft.com/os/v2/open-source.svg?v=103)](https://syknapse.github.io/Contribute-To-This-Project/)
You are right, its should be in English but still it was of no harm when i left it like that.
whats your thoughts , should i mend it...? @waynemorphic

2024-01-16 15:26 UTC, TenTraicion requested changes
Recheck the files, fix if there is anything to fix and mention me after you finish rechecking. Thanks for the update.

2024-01-16 15:26 UTC, TenTraicion commented on translations/README/SWAHILI.md
> +[![Upendo wa Chanzo Wazi](https://badges.frapsoft.com/os/v2/open-source.svg?v=103)](https://syknapse.github.io/Contribute-To-This-Project/)
actually the links and references should be in English, otherwise they won't work.

2024-01-16 15:32 UTC, the1Riddle commented on translations/README/SWAHILI.md
> +[![Upendo wa Chanzo Wazi](https://badges.frapsoft.com/os/v2/open-source.svg?v=103)](https://syknapse.github.io/Contribute-To-This-Project/)
Awesome, i will make all the necessary changes suggested at once before i commit again.

2024-01-16 19:46 UTC, the1Riddle commented
@TenTraicion 

********** **here are the changes made** ****************

1. changing the relevant links back to English
2. made updates from the suggestions made before
and also changed the word `uma` to `fork` as it would have had another meaning, different from the word forking.

2024-01-17 07:47 UTC, the1Riddle commented on translations/README/SWAHILI.md
> +[![Upendo wa Chanzo Wazi](https://badges.frapsoft.com/os/v2/open-source.svg?v=103)](https://syknapse.github.io/Contribute-To-This-Project/)
@waynemorphic what do you think about the current changes..?

2024-01-17 09:05 UTC, waynemorphic approved these changes
LGTM

2024-01-17 10:12 UTC, the-1Riddle commented
> LGTM

Great .

2024-01-17 10:18 UTC, TenTraicion approved these changes
Seems Good

2024-01-17 10:19 UTC, merged

2024-01-17 10:26 UTC, TenTraicion commented
@the1Riddle, Congratulations on your PR Merge, and Thanks for your Contribution.

Welcome to the Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.

2024-01-17 10:47 UTC, the1Riddle commented
> @the1Riddle, Congratulations on your PR Merge, and Thanks for your Contribution.
> 
> Welcome to the Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.

Thanks for considering my contribution.
As i've already joined the discord community, am looking forward to also translate the `Maintainer's Guide` also to Swahili `soon`.

Best regards,

2024-01-17 15:58 UTC, TenTraicion commented
sure, glad to hear that. if you need help or need to contact us, ask in Discord which is the fastest way. Happy Coding..!

2024-01-18 06:50 UTC, kamranzafar4343 reviewed
Looks great now.

2024-02-08 23:04 UTC, olusiekwin reviewed
LGTM