Chard's Card
Syknapse/Contribute-To-This-Project pull request #3508
Opened 2024-01-17 17:44 UTC by ChardPeter

Added a new card and modified the content with my info

2024-01-18 06:35 UTC, TenTraicion requested changes
Hello there @ChardPeter, Thanks for your contribution. Kindly make the requested changes and commit. Thanks.

2024-01-18 06:35 UTC, TenTraicion commented on index.html
> +            <a href="https://x.com/chardpeter1?s=21" target="_blank">Your handle</a>
```suggestion
            <a href="https://x.com/chardpeter1" target="_blank">@chardpeter1</a>
```

2024-01-18 06:35 UTC, TenTraicion commented on index.html
> +            <a href="https://www.github.com/chardpeter" target="_blank">Your handle</a>
```suggestion
            <a href="https://www.github.com/chardpeter" target="_blank">@chardpeter</a>
```

2024-01-18 06:35 UTC, TenTraicion commented on index.html
> +            <p>FreeCodeCamp, Udemy and In person conferences</p>
```suggestion
            <p>3 Useful Dev Resources</p>
```

2024-01-18 06:35 UTC, TenTraicion commented on index.html
> +                <a href="Freecodecamp.org" target="_blank" title="First Resource">Freecodecamp</a>
```suggestion
                <a href="https://freecodecamp.org" target="_blank" title="First Resource">Freecodecamp</a>
```

2024-01-18 06:35 UTC, TenTraicion commented on index.html
> +                <a href="udemy.com" target="_blank" title="Second Resource">udemy</a>
```suggestion
                <a href="https://udemy.com" target="_blank" title="Second Resource">Udemy</a>
```

2024-01-18 06:35 UTC, TenTraicion commented on index.html
> +                <a href="Google.com" target="_blank" title="Third resource">Google</a>
```suggestion
                <a href="https://google.com" target="_blank" title="Third resource">Google</a>
```

2024-01-18 06:35 UTC, TenTraicion commented on index.html
> +        <div class="card">
```suggestion

         <!-- ________ *Peter* Contributor card START________ -->
        <div class="card">
```

2024-01-18 06:35 UTC, TenTraicion commented on index.html
> +        </div>
```suggestion
        </div>
        <!-- ________ *Peter* Contributor card END________ -->
        
```

2024-01-18 06:43 UTC, kamranzafar4343 approved these changes
looks fine to me

2024-01-18 06:49 UTC, TenTraicion commented
> looks fine to me

@kamranzafar4343, Don't mislead people. There are project maintainers who recheck every single commit before approving and merging them.

2024-01-20 06:38 UTC, TenTraicion approved these changes

2024-01-20 06:39 UTC, merged

2024-01-20 06:39 UTC, TenTraicion commented
@ChardPeter, Congratulations on your PR Merge, and Thanks for your Contribution. You can check your card on our [Live Website](https://syknapse.github.io/Contribute-To-This-Project)! It may take 2-3 minutes to make your card visible on our website. 

Welcome to the Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.