Card Created
Syknapse/Contribute-To-This-Project pull request #3547
Opened 2024-02-06 01:59 UTC by kru2710shna

2024-02-06 22:52 UTC, ibrahimdevop21 requested changes
there's a redundancy issue, you have the portfolio link both in the contact section and the resources section ,  try to add any of your favorite learning resources

2024-02-08 00:44 UTC, kru2710shna commented
Changes are made. Can you check please

2024-02-08 14:13 UTC, ibrahimdevop21 requested changes
the twitter link  and handle is wrong
the github handle is wrong ( just exclude Github: from the handle
missing 2 more resources.
optional: missing ending comment and a line break before and after the card

2024-02-08 23:59 UTC, kru2710shna commented
I don't have twitter account!

2024-02-09 09:23 UTC, TenTraicion requested changes
@kru2710shna, Thanks for your contribution. If you don't have twitter you can omit twitter from your card. also you need to add 2 more resources to make that a proper card. Kindly fix the social and add more resources and commit. Thanks

2024-02-09 09:23 UTC, TenTraicion commented on index.html
> +            <a href="https://github.com/kru2710shna" target="_blank">kru2710shna</a>
```suggestion
            <i class="fab fa-github"></i>
            <a href="https://github.com/kru2710shna" target="_blank">kru2710shna</a>
```

2024-02-11 10:02 UTC, TenTraicion requested changes

2024-02-11 10:02 UTC, TenTraicion commented on index.html
> +                  href="krushna27doc@gmail.com"
```suggestion
                  href="https://google.com"
```

2024-02-11 10:02 UTC, TenTraicion commented on index.html
> +                  title="Email"
```suggestion
                  title="Google"
```

2024-02-11 10:02 UTC, TenTraicion commented on index.html
> +                  Contact Me
```suggestion
                 Google
```

2024-02-11 10:03 UTC, TenTraicion approved these changes

2024-02-11 10:03 UTC, merged

2024-02-11 10:03 UTC, TenTraicion commented
@kru2710shna, Congratulations on your PR Merge, and Thanks for your Contribution. You can check your card on our [Live Website](https://syknapse.github.io/Contribute-To-This-Project)! It may take 2-3 minutes to make your card visible on our website. 

Welcome to the Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.