Create URDU.md
Syknapse/Contribute-To-This-Project pull request #3583
Opened 2024-03-01 13:58 UTC by ShadBalti

Close #3497 

Screenshot:
![Screenshot_20240301-185104](https://github.com/Syknapse/Contribute-To-This-Project/assets/134768995/992f7e69-4578-436a-86f7-d54833b85049)

2024-03-02 01:47 UTC, OwlbanGroup commented
Create URDU. md

2024-03-02 13:07 UTC, ShadBalti reviewed
Approve PR

2024-03-06 02:30 UTC, OwlbanGroup commented
Add Urdu Translation for READme file@Owlbangroup

2024-03-08 04:09 UTC, OwlbanGroup commented
Create URDU.md #3585

2024-03-28 01:38 UTC, malakada requested changes
Wow, thanks so much for taking the time to provide a translation for Urdu!! 😍

@ShadBalti -- I don't speak/read Urdu, so I have some questions about the content if you can help me out. :) I noticed that you left the commit message in English -- would this be common practice for most developers out of Pakistan/India/elsewhere? If so, is there an explanation in Urdu telling the reader that while Urdu may be their primary language that it's customary to write a commit message in English still? If you don't know, I can reach out to some other devs I know in Pakistan at least and ask their opinion.

This PR looks great, but I'd like to ask that you add a few more commits so that it matches what we're looking for with new translations that make it easier for folks to benefit from your work:

- [ ] add a link to your README translation to `/translations/README.md` (https://github.com/Syknapse/Contribute-To-This-Project/tree/master/translations), placed in alphabetical order (looks like it'll be easy for you as it'll go right after Ukranian!)

If you've never worked with Markdown tables before, here's a helpful guide from Github about it: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-tables, and if you have questions feel free to ping me on the Discord (https://discord.gg/ZtgtthHYUt) in the `#github-help` channel (I'm malakada on Discord as well!). 😄 

Great work over all though and I'm super excited to approve this after you add a link to it!! 🎉

2024-04-05 08:25 UTC, malakada commented
Hey @OwlbanGroup -- I know this has been sitting for a long time before getting some attention. Are you still interested in this? If so, we'd be very happy to help you get this merged in. :)

2024-04-05 18:42 UTC, OwlbanGroup commented
Yes I am thank you.

2024-04-06 01:02 UTC, malakada commented
@OwlbanGroup let's do it then! 🎉 

Just need to add a link to your translation in `/translations/README.md`. I put some helpful links here: https://github.com/Syknapse/Contribute-To-This-Project/pull/3583#pullrequestreview-1965016620

Do you need help with this?

2024-04-06 05:05 UTC, OwlbanGroup commented
Yes I do

On Fri, Apr 5, 2024, 9:02 PM Malak ***@***.***> wrote:

> @OwlbanGroup <https://github.com/OwlbanGroup> let's do it then! 🎉
>
> Just need to add a link to your translation in /translations/README.md. I
> put some helpful links here: #3583 (review)
> <https://github.com/Syknapse/Contribute-To-This-Project/pull/3583#pullrequestreview-1965016620>
>
> Do you need help with this?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Syknapse/Contribute-To-This-Project/pull/3583#issuecomment-2040837114>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BB4X3U3F3ZG6DB5N47NTN33Y35CTNAVCNFSM6AAAAABEB2MTLGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANBQHAZTOMJRGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-07-24 12:06 UTC, ShadBalti commented
Now it's ready.

2024-07-25 08:46 UTC, ShadBalti commented
#3583 ready

2024-07-25 08:52 UTC, ShadBalti commented
Close  #3497

2024-09-20 09:42 UTC, TenTraicion requested changes
hello @ShadBalti , Thanks for your contribution. sorry for the late reply, here are some concerns about your contribution:
- This file seems incomplete
- there are some URL issue in this file
- a link to this file should be in translation doc
- the image contents are missing
Kindly fix those and let me know, and it will be awesome if you can translate the terminal tutorial too.

2024-09-20 09:42 UTC, TenTraicion commented on translations/README/URDU.md
> +- [اوپر 100 شراکت دار](#top-100-contributors)
the links should be fixed

2024-09-20 09:42 UTC, TenTraicion commented on translations/README/URDU.md
> +[![فارک کریں](https://img.shields.io/github/forks/Syknapse/Contribute-To-This-Project.svg?style=social)][twit]
the twit icons should be on top of the file

2024-09-29 02:42 UTC, closed without merging