Ecos's card
Syknapse/Contribute-To-This-Project pull request #3588
Opened 2024-03-04 16:30 UTC by eco-akram

Added a new card :)

2024-03-04 20:59 UTC, Amazening requested changes
Hey there, looks pretty good!

Just two things to note before I approve your request

- You haven't provided a link to _your_ specific GitHub handle, only the main GitHub website. Give that a quick fix.
- Your code is indented to the right - try and align it with the other cards

Other than that your code seems to look good! Just make those changes and I'll happily merge your pull request. Good luck!

2024-03-06 11:38 UTC, eco-akram commented
Hi!
I have resolved the issue.

2024-03-09 17:54 UTC, TenTraicion requested changes

2024-03-09 17:54 UTC, TenTraicion commented on index.html
> +                <a href="freecodecamp.org" target="_blank" title="First Resource">FreeCodeCamp</a>
```suggestion
                <a href="https://freecodecamp.org" target="_blank" title="First Resource">FreeCodeCamp</a>
```

2024-03-09 17:55 UTC, TenTraicion approved these changes

2024-03-09 17:56 UTC, merged

2024-03-09 17:57 UTC, TenTraicion commented
@eco-akram, Congratulations on your PR Merge, and Thanks for your Contribution. You can check your card on our [Live Website](https://syknapse.github.io/Contribute-To-This-Project)! It may take 2-3 minutes to make your card visible on our website. 

Welcome to the Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.