Add my card information - Coding_Dynasty
Syknapse/Contribute-To-This-Project pull request #3640
Opened 2024-04-03 18:03 UTC by coding-dynasty

2024-04-03 18:04 UTC, coding-dynasty commented
Add my card information

2024-04-05 07:54 UTC, theAravinthM requested changes

2024-04-05 07:54 UTC, theAravinthM commented on .gitignore
> +.gitpod.yml
Hi @coding-dynasty, Why did you add this `.gitpod.yml` in this commit. Could you remove it recommit so that we can merge your PR. Thx.

2024-04-05 07:54 UTC, theAravinthM commented on index.html
> +
With these changes we are good to merge this PR.

2024-04-05 08:35 UTC, theAravinthM approved these changes

2024-04-05 08:35 UTC, merged