Daniel Lounsbury
Syknapse/Contribute-To-This-Project pull request #3659
Opened 2024-04-05 19:30 UTC by BigSkyCoder2003

Add my card information

2024-04-06 00:47 UTC, malakada requested changes
Awesome job @BigSkyCoder2003! Your card looks great, and I'd love to get your merged in... but there's extra templating code that looks like you accidentally duplicated into the file. 😅 

These things happen all the time, it's part of why we have a code review process. 😄 Just delete the extra empty template, make a new commit, and push it up. Easy peasy. 💪 

We'll come by and look at it again to see if you've been able to update it, but if you're feeling excited feel free to ping in the Discord.

2024-04-06 00:47 UTC, malakada commented on index.html
> +
Looks like you accidentally duplicated another template block here which would be very confusing for future contributors (like yourself!) who want to put their card in the right place.

Can you please remove this extra template so we can get your PR merged? :D

2024-04-12 21:57 UTC, BigSkyCoder2003 commented
Should have that fixed now! Please let me know if there is anything else I should do! Thank you for your feedback!

2024-04-21 09:05 UTC, malakada commented on index.html
> +          <p class="about">I am a person</p>
lmao, love it haha

2024-04-21 09:08 UTC, malakada requested changes
Sorry I didn't notice it the first time around, but you should update your links to point to your profile. :)

2024-04-21 09:08 UTC, malakada commented on index.html
> +            <a href="https://www.instagram.com/" target="_blank">daniel.loun</a>
Hey! This link doesn't go to your profile! Can you update it? :S

2024-04-21 09:08 UTC, malakada commented on index.html
> +            <a href="https://www.github.com" target="_blank">BigSkyCoder2003</a>
Same here -- link doesn't go to your profile.

2024-04-21 09:08 UTC, malakada commented on index.html
> +                <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" target="_blank" title="Third resource">Good Talk</a>
🏆

2024-04-24 17:43 UTC, TenTraicion approved these changes

2024-04-24 17:43 UTC, merged

2024-04-24 17:43 UTC, TenTraicion commented
@BigSkyCoder2003, Congratulations on your PR Merge, and Thanks for your Contribution. You can check your card on our [Live Website](https://syknapse.github.io/Contribute-To-This-Project)! It may take 2-3 minutes to make your card visible on our website. 

Welcome to the Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.