Update index.html
Syknapse/Contribute-To-This-Project pull request #3718
Opened 2024-04-19 19:10 UTC by prakharagrawal10

added card

2024-04-19 19:10 UTC, prakharagrawal10 commented
prakhars card

2024-04-20 05:37 UTC, CandidDeer requested changes
Please provide 3 useful resources. Thx.

2024-04-22 08:59 UTC, StackOverflowIsBetterThanAnyAI reviewed
I added some suggestions to your code

2024-04-22 08:59 UTC, StackOverflowIsBetterThanAnyAI commented on index.html
> +            <a href="https://www.github.com/prakhar-agra-10" target="_blank">prakhar-agra-10</a>
```suggestion
            <a href="https://github.com/prakharagrawal10" target="_blank">prakharagrawal10</a>
```
this is your correct github url

2024-04-22 08:59 UTC, StackOverflowIsBetterThanAnyAI commented on index.html
> +            <a href="https://www.twitter.com/your_user_handle" target="_blank">Your handle</a>
if you have an x / a twitter account please use your correct link and name

2024-04-22 08:59 UTC, StackOverflowIsBetterThanAnyAI commented on index.html
> +          <p class="about">about you</p>
write something about you

2024-04-22 08:59 UTC, StackOverflowIsBetterThanAnyAI commented on index.html
> +                <a href="#" target="_blank" title="First Resource">StackOverflow</a>
```suggestion
                <a href="https://github.com/prakharagrawal10" target="_blank" title="Stack Overflow">Stack Overflow</a>
```

2024-04-22 08:59 UTC, StackOverflowIsBetterThanAnyAI commented on index.html
> +                <a href="#" target="_blank" title="Second Resource">Free Code Camp</a>
```suggestion
                <a href="https://www.freecodecamp.org/" target="_blank" title="freeCodeCamp">freeCodeCamp</a>
```

2024-04-22 08:59 UTC, StackOverflowIsBetterThanAnyAI commented on index.html
> +                <a href="#" target="_blank" title="Third resource">Chat GPT</a>
```suggestion
                <a href="https://chat.openai.com/" target="_blank" title="ChatGPT">ChatGPT</a>
```

2024-04-26 05:37 UTC, TenTraicion requested changes

2024-04-26 05:37 UTC, TenTraicion commented on index.html
> +            <a href="https://www.twitter.com/your_user_handle" target="_blank">Your handle</a>
```suggestion
          <p class="name">Prakhar</p>
          <p class="contact">
```

2024-04-26 05:37 UTC, TenTraicion approved these changes

2024-04-26 05:39 UTC, TenTraicion approved these changes

2024-04-26 05:39 UTC, merged

2024-04-26 05:40 UTC, TenTraicion commented
@prakharagrawal10, Congratulations on your PR Merge, and Thanks for your Contribution. You can check your card on our [Live Website](https://syknapse.github.io/Contribute-To-This-Project)! It may take 2-3 minutes to make your card visible on our website. 

Welcome to the Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.