Update index.html
Syknapse/Contribute-To-This-Project pull request #3739
Opened 2024-05-03 14:30 UTC by MJujh

"Added my information on to my card" Thank for being a helpful project

2024-05-03 16:23 UTC, theAravinthM requested changes
Hi @MJujh 
Your PR is very close to getting merged :-) Everything seems good except two lines. The PR needs corrections on 2 lines. Make those corrections & commit, so that I can merge your PR. I have also provided you the comments on the lines to guide to that.

2024-05-03 16:23 UTC, theAravinthM commented on index.html
> +            <p >Your handle</p>
Since these lines make no sense & does not rely on the template, kindly remove these lines.

2024-05-05 10:41 UTC, MJujh commented
Sorry the delayed respond i have remove the not needed line thanks for pointing the issue out to me

2024-05-05 14:15 UTC, theAravinthM commented
Hey great that you made the modifications & your PR is ready to get merged 🎉
Congratulations on your PR Merge, and Thanks for your Contribution! Your card will be live on our Website in a moment!

Now you can follow the Next Steps. You are also welcome to join our Discord Server: https://discord.gg/tWkvS4ueVF and be a part of our community.

Happy contributing!

2024-05-05 14:15 UTC, merged