Addding my card.
Syknapse/Contribute-To-This-Project pull request #3775
Opened 2024-05-22 15:40 UTC by hauphanlvc

Signed-off-by: Hau Trong Phan <hauphanlvc@gmail.com>

2024-05-22 15:51 UTC, hauphanlvc commented
Thanks for helping us to have a place to get the first contribution.

2024-05-23 16:34 UTC, theAravinthM requested changes
Hi @hauphanlvc Happy that you made a Pull Request and made your first open source contribution! 
Your PR needs a slight change to get merged! Get back with the updations sooner to successfully make your PR merged!

2024-05-23 16:34 UTC, theAravinthM commented on index.html
> +          </div>
In this resources section, providing 3 helpful online resources is a good practice! It seems you have provided 1 resource link, which is fine. But, adding two more is recommended. 

You could add any resource link that the fellow developers could make use of !

2024-05-24 04:01 UTC, hauphanlvc commented
I have added more new resources, please help me to check it. Thank you !!!

2024-05-24 05:52 UTC, theAravinthM commented
Congratulations on your PR Merge, and Thanks for your Contribution! Your card will be live on our Website in a moment! 🚀

Now you can follow the Next Steps. You are also welcome to join our Discord Server: https://discord.gg/tWkvS4ueVF and be a part of our community.

Happy contributing!

2024-05-24 05:52 UTC, merged