Add wviie card
Syknapse/Contribute-To-This-Project pull request #3811
Opened 2024-06-13 22:21 UTC by wviie

Added my card with my info

2024-06-14 12:24 UTC, ibrahimdevop21 requested changes
Hi @wviie,
Thank you for your contribution and welcome to the open-source community! Before we can proceed, a few changes are needed. Your code is altering a significant portion of our code base, which isn't necessary. Please follow the instructions outlined in our [contributors guide](https://github.com/Syknapse/Contribute-To-This-Project/tree/master).

Looking forward to your revised submission!

2024-06-14 14:15 UTC, wviie commented
Hi @ibrahimdevop21,
Changes have been made, hopefully this fixes the problem?

2024-06-15 18:55 UTC, TenTraicion approved these changes

2024-06-15 18:56 UTC, merged

2024-06-15 18:57 UTC, TenTraicion commented
@wviie, Congratulations on your PR Merge, and Thanks for your Contribution. You can check your card on our [Live Website](https://syknapse.github.io/Contribute-To-This-Project)! It may take 2-3 minutes to make your card visible on our website. 

Welcome to the Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.