Add Persian translation for `Readme.md`
Syknapse/Contribute-To-This-Project pull request #3867
Opened 2024-07-20 15:28 UTC by Mobinshahidi

### What was done?
- Added Persian (Farsi) translation to `Readme.md`.
- Updated the translation table and included a link to `Farsi.md`.

### What are the next steps?
- Translate `maintainer_guide.md` to Persian.
- Translate `terminal_tutorial.md` to Persian.

2024-07-22 22:36 UTC, Mobinshahidi commented
Hi, how are you?
Can you review my changes please so i can start translating rest of the readme?

@CandidDeer

2024-07-29 10:44 UTC, CandidDeer commented
@Mobinshahidi Since I don't know the Persian language, I'm afraid I can't really give any input, sorry!

2024-07-29 16:13 UTC, Mobinshahidi commented
So if someone who knows persian, review this PR and approved its ok?
@CandidDeer

2024-09-20 09:54 UTC, TenTraicion requested changes
Hello there @Mobinshahidi, Thanks a bunch for the translation, i really appreciate your work. Kindly remove the html tags or any other element except markdown syntax and text, and this file is good to be merged. Lo0king forward to terminal tutorial translation. 

also kindly rename the file name to: PERSIAN.md and also link the file in translation.md/ Thanks.

2024-09-23 11:45 UTC, Mobinshahidi commented
Thank you so much for your review @TenTraicion.
The html tags is because that persian language is RTL and because of that i used the html tags and without them is not looking good.
Whats your opinion?

2024-09-23 16:53 UTC, TenTraicion commented
@Mobinshahidi, hello there. I understand your situation. But since this year, we discourage contributors to use any kind of external tags/codes unless it's approved by github markdown language. So kindly use only Github Markdown for .md files.

2024-09-28 00:24 UTC, Mobinshahidi commented
@TenTraicion hi how are you?
i did what you told me, please check them again.
thanks

2024-09-30 08:09 UTC, TenTraicion requested changes
@Mobinshahidi, kindly fix the mentioned issues and we are good to merge this file. Thanks.

2024-09-30 08:09 UTC, TenTraicion commented on translations/README/PERSIAN.md
> +- [100 مشارکت کننده برتر](#top-100-contributors)
need to fix the links in this content table. most of the links are not working!

2024-09-30 08:09 UTC, TenTraicion commented on translations/README/PERSIAN.md
> +  [Spanish (Español)](/translations/README/SPANISH.md) | [Turkish (Türkçe)](/translations/README/TURKISH.md) | [Ukrainian (українська)](/translations/README/UKRAINIAN.md) | [Norwegian (Norsk)](/trans
the link in Persian language should be `/translation/README/PERSIAN.md` according to the file name. also don't put it here, as it is the Persian translation file, you need to fix the link in other files where you've mentioned this translation.

2024-09-30 08:09 UTC, TenTraicion commented on translations/README/PERSIAN.md
> +[↑ به بالا برو ↑](#)
the go up link in your translation should be something like: `#فهرست-دسترسی-سریع`

2024-10-06 02:41 UTC, closed without merging