add my Profile Card
Syknapse/Contribute-To-This-Project pull request #697
Opened 2020-12-03 15:53 UTC by pauloeduardomc

Add my Profile Card

2021-01-07 19:04 UTC, eligifty-coder requested changes
Kindly effect the corrections requested

2021-01-07 19:04 UTC, eligifty-coder commented on index.html
> -        <!-- COPY everything ABOVE this, from contributor card start to end along with the "START" and "END" comment lines -->
We do not want you to delete this line.

2021-01-07 19:04 UTC, eligifty-coder commented on index.html
> +          <!-- ________ Contributor's card END ________  -->
Kindly take your entire card and paste it below the line that says "Paste Your Card Directly Below this Line"

2021-01-31 20:17 UTC, Syknapse commented
Manually fixed the problem and merged the card. Closing this PR now

2021-01-31 20:17 UTC, closed without merging