Suraj Sarangi is on the page
Syknapse/Contribute-To-This-Project pull request #804
Opened 2021-04-17 13:05 UTC by SurajSarangi

Added my card to contribute to the repo. Hope it gets merged

2021-07-10 15:12 UTC, lax0248917 requested changes
Let us know if you have any questions. 👍

2021-07-10 15:12 UTC, lax0248917 commented on index.html
Hello @SurajSarangi, thank you for contributing. There are some changes that need to be made to your index.html file. Please remove this blank line and be sure to run `npm run prettier-html` to insure that your file meets the styling requirements. Thank you.

2021-07-11 12:54 UTC, SurajSarangi commented
I removed the blank line as mentioned. There still seems to be conflicts however. Anything I can do? Thanks

2021-07-11 13:27 UTC, merged

2021-07-11 13:28 UTC, lax0248917 commented
Hello @SurajSarangi, you are all set. I went ahead and resolved any merge conflicts. Thank you for your contribution and good luck with open source in the future. Take care 🚀