index.html
Syknapse/Contribute-To-This-Project pull request #974
Opened 2021-09-19 07:07 UTC by ROHIT-ROSHAN

2021-09-19 08:01 UTC, iatharva commented on index.html
> +        <!-- ________ *TEMPLATE: MAKE A COPY* Contributor card START ________  -->
Just replace ' *TEMPLATE: MAKE A COPY*' with your name

2021-09-19 08:02 UTC, iatharva commented on index.html
> +        <!-- ________*END TEMPLATE* Contributor card END ________  -->
Just replace ' *END TEMPLATE*' with your name

2021-09-19 08:02 UTC, iatharva requested changes
Once the changes are done I will merge your pull request. :)

2022-04-12 04:50 UTC, ana-vela commented
Hi, @ROHIT-ROSHAN Thank you for submitting this pull request. We are closing pull requests that have been inactive for several months. Please feel free to start over and create a new pull request if you would like to contribute to this project. Thanks!

2022-04-12 04:50 UTC, closed without merging